const questionBank = {
  mcq: [
    { q: "What is the primary characteristic of Lossless Compression?", options: ["It uses Fourier Transformation", "Origin data is recreated with no data loss", "It eliminates unimportant data", "The resulting file is always larger"], answer: "Origin data is recreated with no data loss", explanation: "Lossless compression guarantees the original data can be reconstructed exactly, bit-for-bit, without losing any information.<br><br>💡 **Real-Life Example:** Imagine packing a suitcase. You fold your clothes perfectly (compress) to fit them all in. When you arrive at your hotel and unpack (decompress), every single piece of clothing is still there, exactly as it was. A ZIP file on your computer does exactly this." },
    { q: "Which algorithm is an example of Lossy Compression?", options: ["Run-Length Encoding (RLE)", "Huffman coding", "LZW algorithm", "JPEG compression"], answer: "JPEG compression", explanation: "JPEG compression drastically reduces image sizes by permanently destroying 'unimportant' visual data (usually high-frequency details) using complex math.<br><br>💡 **Real-Life Example:** It is like summarizing a 500-page book into a 10-page essay. The essay is much smaller and easier to carry, and you get the main idea of the story, but you can NEVER rebuild the exact original 500 pages from it. The extra details are lost forever." },
    { q: "If an original file is 200 KB and the compressed file is 50 KB, what is the compression ratio?", options: ["2:1", "4:1", "10:1", "5:1"], answer: "4:1", explanation: "Compression ratio is simply Original Size divided by Compressed Size (200 / 50 = 4).<br><br>💡 **Real-Life Example:** If you had a giant fluffy pillow (200 cubic inches) and you squished it down into a vacuum-seal bag until it was only 50 cubic inches, it is now 1/4th of its original size. The ratio is 4-to-1." },
    { q: "Which algorithm optimally encodes characters based on their frequency of occurrence?", options: ["LZW", "Huffman Coding", "RLE", "Fourier Transform"], answer: "Huffman Coding", explanation: "Huffman coding assigns very short binary codes to common letters (like 'E') and long binary codes to rare letters (like 'Z').<br><br>💡 **Real-Life Example:** Think of Morse Code. A very common letter like 'E' is just a single short dot ( . ). A rare letter like 'Q' is a long sequence ( --.- ). This ensures that the most common messages take the shortest amount of time to tap out." },
    { q: "What does LZW stand for (conceptually in class)?", options: ["Lempel-Ziv-Welch", "Light-Zone-Weight", "Lossless-Zero-Width", "Luminance-Z-Wave"], answer: "Lempel-Ziv-Welch", explanation: "Lempel-Ziv-Welch builds a dictionary of repeated patterns 'on the fly' as it compresses data.<br><br>💡 **Real-Life Example:** If you are texting a friend repeatedly about 'University of Northampton', it takes a long time to type. LZW mathematically figures out that phrase happens a lot, and assigns it an automatic shorthand like '!1'. Next time it sees 'University of Northampton', it just saves '!1', making the file tiny." },
    { q: "Visible light wavelength ranges from:", options: ["Infrared to Ultraviolet", "Red to Violet", "Green to Blue", "Cyan to Magenta"], answer: "Red to Violet", explanation: "Visible light in the electromagnetic spectrum stretches from Red (longer, lazy waves) to Violet (shorter, energetic waves).<br><br>💡 **Real-Life Example:** Look at a rainbow! It always starts with Red on the outside and ends with Violet on the inside. Everything else, like X-rays or Radio waves, is invisible to us." },
    { q: "How does the human eye perceive different colours?", options: ["Through two lenses", "Through rods only", "Through three types of cones", "Through cornea reflections"], answer: "Through three types of cones", explanation: "The eye has three types of receptors called cones; one prefers Red light, one prefers Green, and one prefers Blue.<br><br>💡 **Real-Life Example:** Think of your eye like a bucket of three different paints. By mixing just those three primary paints (red, green, blue cones firing off in your brain at different intensities), your brain invents every other colour you see, like yellow or purple." },
    { q: "Which properties typically define colour in computer graphics models?", options: ["Red, Orange, Yellow", "Hue, Saturation, and Luminance", "Bit, Byte, Nibble", "Vector, Raster, Pixel"], answer: "Hue, Saturation, and Luminance", explanation: "These properties describe colour intuitively. Hue is the base color, Saturation is the purity, and Luminance is the brightness.<br><br>💡 **Real-Life Example:** Imagine buying paint. 'Hue' is picking Red. 'Saturation' is choosing between a bright fire-engine Red or a faded, washed-out greyish-Red. 'Luminance' is whether you shine a bright flashlight on that paint (bright) or turn off the lights entirely (pitch black)." },
    { q: "In older Cathode Ray Tube (CRT) televisions, how was the picture scanned?", options: ["Vector scanning from center", "Raster Scan System", "Digital projection", "Quantum dots"], answer: "Raster Scan System", explanation: "The electron beam swept across the screen one row at a time, moving from left to right, and top to bottom.<br><br>💡 **Real-Life Example:** Think of reading a book or painting a fence. You read from left to right across the top line, then drop down and read the next line, left to right, all the way to the bottom. A CRT drew the picture the exact same way at blinding speed." },
    { q: "What hardware component holds the set of intensity values defining a CRT/monitor picture?", options: ["CPU Cache", "Hard Drive", "Frame buffer", "Sound Card"], answer: "Frame buffer", explanation: "Picture definition is stored in a specialised memory called a frame buffer before it reaches the screen.<br><br>💡 **Real-Life Example:** Think of a chef in a restaurant. The frame buffer is the 'waiter's tray'. The computer (chef) builds the complete picture and places it on the tray. Then, the tray (frame buffer) immediately carries it perfectly to the screen (customer) instantly." },
    { q: "What is the primary purpose of a smoothing spatial filter?", options: ["Sharpen edges", "Blur the image and reduce noise", "Change the image hue", "Compress the image size"], answer: "Blur the image and reduce noise", explanation: "Smoothing filters act as weighted averages, reducing sharp intensity transitions.<br><br>💡 **Real-Life Example:** Imagine a bumpy, rocky gravel road (image noise). A smoothing filter is like pouring hot asphalt over the gravel and rolling it flat. It removes the sharp bumps and makes everything locally blend together smoothly, but it makes the road blurrier to look at." },
    { q: "When modifying an edge pixel using a 3x3 filter, what is the 'Zero-Padding' solution?", options: ["Deleting the image", "Adding a border of zeroes around the image", "Multiplying by zero", "Setting all pixels to zero"], answer: "Adding a border of zeroes around the image", explanation: "Zero-padding adds a theoretical ring of 0s outside the image so the math can complete without crashing.<br><br>💡 **Real-Life Example:** Imagine you are laying 3x3 square tiles on a floor, but you reach the wall. Your tile hangs over the edge into empty space. Zero-Padding is like pretending there is invisible floor outside the house to temporarily support your tile so you can finish laying it." },
    { q: "What property does an affine transformation mathematically preserve?", options: ["Colour values", "Image file extension", "Parallel lines", "Pixel grouping"], answer: "Parallel lines", explanation: "An affine transformation is a linear mapping (Scaling, Translation, Shearing) that ensures sets of originally parallel lines never cross.<br><br>💡 **Real-Life Example:** Think of drawing a grid on a rubber sheet. If you pull the sheet sideways (shearing) or stretch it (scaling), the grid lines will slant or grow, but the lines that used to be parallel will *still* be parallel. They will never suddenly intersect." },
    { q: "In Python, which keyword is fundamentally used to define a new function?", options: ["func", "def", "function", "lambda"], answer: "def", explanation: "The 'def' keyword introduces a reusable function definition.<br><br>💡 **Real-Life Example:** Like naming a recipe! `def bake_cake():` tells the kitchen (Python) that whenever you yell 'bake_cake()', it needs to execute the specific baking instructions you typed inside that block." },
    { q: "If a JPEG image is continually compressed and decompressed multiple times, what happens?", options: ["Nothing, it is lossless", "Generation loss occurs due to cumulative data discarding", "File size increases automatically", "It converts to a PNG"], answer: "Generation loss occurs due to cumulative data discarding", explanation: "Lossy algorithms throw away detailed math every time they save. Resaving it repeatedly destroys it.<br><br>💡 **Real-Life Example:** Imagine photocopying a picture. Then you take that photocopy, and photocopy *it*. The third time, you photocopy that photocopy. Eventually, the picture turns into a blurry, blocky mess. That is exactly what happens if you repeatedly save a JPEG over and over." },
    { q: "Which of the following is an example of an immutable sequence in Python?", options: ["List", "Dictionary", "Set", "Tuple"], answer: "Tuple", explanation: "Once initialized, you cannot alter the size or contents of a standard Python tuple.<br><br>💡 **Real-Life Example:** A List `[]` is a whiteboard; you can erase things and draw new ones. A Tuple `()` is a tattoo; whatever you wrote when you created it is permanent and cannot be deleted or changed." },
    { q: "What mathematical operation is the foundation of applying a spatial filter kernel across an entire image?", options: ["Matrix Transpose", "Fourier Transform", "Convolution / Correlation", "Cross Product"], answer: "Convolution / Correlation", explanation: "Kernels are multiplying matrices placed over image matrices systematically.<br><br>💡 **Real-Life Example:** Think of having a small magnifying glass (your kernel) that changes the color of anything underneath it. You slide the magnifying glass across a giant map (the image) pixel by pixel, altering the map precisely as you move. This sliding math operation is convolution." },
    { q: "Which colour model is traditionally used for physical color printing?", options: ["RGB", "HSB", "CMYK", "YUV"], answer: "CMYK", explanation: "Cyan, Magenta, Yellow, and Key (Black) are subtractive colors used for ink.<br><br>💡 **Real-Life Example:** Monitors use light (RGB), which gets brighter the more you add. But on totally white paper, adding colored ink makes it *darker*. So physical printers use Cyan, Magenta, Yellow, and Black ink to filter light out of the white paper." }
  ],
  fillInTheBlank: [
    { q: "Compression is the process of transforming ______ data to a compressed format.", answer: "raw", explanation: "Compression converts bulky unoptimized data into efficiently encoded data.<br><br>💡 **Real-Life Example:** Taking all your loose 'raw' clothes scattered in the bedroom and tightly folding them into a suitcase." },
    { q: "A compression method is considered ______ if the exact original data can be 100% recovered without fail.", answer: "lossless", explanation: "Lossless means zero original bits are permanently altered. <br><br>💡 **Real-Life Example:** A ZIP file wrapping a word document. If the ZIP lost a single letter, the document would be ruined." },
    { q: "______ is an example of a simple algorithm that counts consecutive repeated identical characters natively.", answer: "RLE", explanation: "Run-Length Encoding compresses 'AAAABBB' into '4A3B'. <br><br>💡 **Real-Life Example:** Saying 'I have 5 apples' is much faster than saying 'I have an apple, an apple, an apple, an apple, and an apple'." },
    { q: "In a CRT screen, the picture is drawn by firing an ______ beam at the front glass.", answer: "electron", explanation: "The TV blasts electrons at phosphors which light up. <br><br>💡 **Real-Life Example:** Like turning on a garden hose and spraying water back and forth across a dirty wall to clean a specific shape." },
    { q: "The pattern of moving from left-to-right, row-by-row top-to-bottom is known as a ______ scan system.", answer: "raster", explanation: "Raster scanning was how old displays updated entirely uniformly. <br><br>💡 **Real-Life Example:** Like a lawnmower cutting a massive field by making continuous straight horizontal sweeps across the grass, dropping down slightly each pass." },
    { q: "In the human eye, biological sensors called ______ are primarily responsible for perceiving bright colour.", answer: "cones", explanation: "Cones handle Red/Green/Blue, while Rods handle dim grayscale light. <br><br>💡 **Real-Life Example:** Think of cones as high-definition expensive daylight cameras, and rods as cheap blurry night-vision cameras." },
    { q: "Hue, Saturation, and ______ are three main properties of colour commonly separated in computer graphics.", answer: "luminance", explanation: "Luminance represents the brightness of the pixel decoupled from its actual Hue. <br><br>💡 **Real-Life Example:** Luminance is like adjusting the dimmer switch on your lightbulb. The red wall is still exactly 'Red' (Hue), but turning the dial changes how bright it is (Luminance)." },
    { q: "Applying a weighted 3x3 averaging filter matrix to an image will visually ______ it.", answer: "blur", explanation: "Averaging local neighbourhoods acts as a low-pass filter, flattening sharp changes. <br><br>💡 **Real-Life Example:** If you take a sharp photograph and rub your thumb aggressively across the wet ink, you mix the sharp colors together, creating a soft blur." },
    { q: "A linear math mapping method that guarantees previously parallel lines remain parallel is called an ______ transformation.", answer: "affine", explanation: "Affine geometry allows scaling, shearing, rotating, and translating. <br><br>💡 **Real-Life Example:** Drawing two parallel train tracks on the side of a balloon. No matter how much you inflate (scale) the balloon, those tracks will stretch but never cross." },
    { q: "In Python, ______ are mandatory structural tools used to outline which code blocks belong to `if` statements.", answer: "indentation", explanation: "Python relies on spaces instead of `{}` brackets. <br><br>💡 **Real-Life Example:** In a grocery list, you visually indent 'Apples' and 'Oranges' under the heading 'Fruit' so you know they belong there. Python uses this visual rule to actually run the program." },
    { q: "Unlike lists, Python ______ use parentheses `()` and their data cannot be changed safely after creation.", answer: "tuples", explanation: "Tuples are immutable locked collections. <br><br>💡 **Real-Life Example:** Setting the dimensions of your TV screen (1920, 1080). You never want a math error to accidentally change your physical TV width to 5, so you use a protective Tuple." },
    { q: "To perform matrix operations incredibly fast on an OpenCV image, one heavily uses the ______ math library in Python.", answer: "numpy", explanation: "Numpy overrides Python's slow loops with lightning-fast C-code backgrounds. <br><br>💡 **Real-Life Example:** Trying to do complex math by hand (pure Python) versus handing the math to an automated supercomputer calculator (Numpy)." },
    { q: "Translating an image mathematically shifts its pixels along the _ and _ axes linearly.", answer: "x and y", explanation: "Translation moves geometry around the frame. <br><br>💡 **Real-Life Example:** Playing chess. Moving a pawn from square D2 to D4 doesn't rotate or shrink the pawn; it simply alters its X,Y grid coordinates." },
    { q: "An image represented by a mathematical formula (lines and curves) rather than a grid of physical pixels is called a ______ graphic.", answer: "vector", explanation: "Vectors are math, allowing infinite zooming. <br><br>💡 **Real-Life Example:** Imagine taking a tiny photo and zooming in until it looks like blocky Lego (Raster/Bitmap). Vector graphics are like a rubber band pulled between two nails; if you walk backward, it scales infinitely without ever looking blocky." }
  ],
  matchFollowing: [
    {
      q: "Match the following compression tools to their real-life analogies",
      pairs: [
        { left: "Lossless Compression", right: "Packing a parachute perfectly so it opens safely" },
        { left: "Lossy Compression", right: "Trimming a novel down to a Wikipedia summary" },
        { left: "Huffman Encoding", right: "Using Morse Code for frequent letters" },
        { left: "Run Length Encoding (RLE)", right: "Saying 'Five Apples' instead of 'Apple Apple Apple Apple Apple'" }
      ],
      explanation: "💡 Connecting complex math algorithms to everyday actions makes them obvious. Lossy destroys data (like summarizing a book). Lossless preserves exactly everything."
    },
    {
      q: "Match the TV/Screen terms to their real-life actions",
      pairs: [
        { left: "Raster Scan", right: "Painting a wall row-by-row, top to bottom" },
        { left: "Refresh Rate", right: "Flipping through a flipbook of drawings rapidly" },
        { left: "Monochrome Display", right: "Watching an old black and white TV" },
        { left: "Frame Buffer Memory", right: "A waiter holding the chef's finished plate, ready for the customer" }
      ],
      explanation: "💡 Monitors are just extremely fast analogue/digital converters tricking your eyes using grids."
    },
    {
      q: "Match the Spatial Filtering concepts to physical actions",
      pairs: [
        { left: "Smoothing Filter", right: "Rubbing your thumb over wet ink to blend it" },
        { left: "Sharpening Filter", right: "Tracing the edges of a shape with a dark marker" },
        { left: "Zero-padding edge fix", right: "Pretending there are black invisible pixels outside the photo" },
        { left: "Convolution Matrix Math", right: "Sliding a colour-changing magnifying glass across a map" }
      ],
      explanation: "💡 Filtering doesn't 'know' what the picture is, it just runs blind math blindly sliding across the pixels."
    },
    {
      q: "Match the Python structures to real-life equivalents",
      pairs: [
        { left: "List [ ]", right: "A whiteboard list where you can constantly erase and add items" },
        { left: "Tuple ( )", right: "A tattoo. Once written, it can never be changed" },
        { left: "Indentation", right: "Formatting a grocery list with indented sub-categories" },
        { left: "OpenCV Library", right: "A pre-built heavy factory that processes images for you" }
      ],
      explanation: "💡 Python is fundamentally built to be readable and logical, mimicking human reasoning patterns through structures like Lists and Indentations."
    }
  ],
  trueFalse: [
    { q: "A compression ratio of 2:1 means the compressed file is half the size of the original.", answer: "True", explanation: "Original (2) divided by Compressed (1) = 2. <br><br>💡 **Real-Life Example:** Squeezing a massive sleeping bag into a tiny stuff sack that takes up exactly half the space in your hiking bag." },
    { q: "JPEG uses math like 'Discrete Cosine Transforms' to permanently throw away visual data, making it a lossy format.", answer: "True", explanation: "JPEG isolates high-frequency pixels and discards them because our brains don't notice. <br><br>💡 **Real-Life Example:** Stripping the extremely high-pitched sounds out of an MP3 song because humans can only hear up to a certain pitch anyway." },
    { q: "If you tilt an image so its sides slant (Shearing), the straight sides become warped and wavy like a funhouse mirror.", answer: "False", explanation: "Shearing maintains perfectly straight parallel lines. <br><br>💡 **Real-Life Example:** Pushing on the side of a deck of playing cards. The deck tilts diagonally, but the sides remain perfectly smooth and straight, never wavy." },
    { q: "LZW compression doesn't require an enormous dictionary attached to the file because it logically re-builds the dictionary while you unzip it.", answer: "True", explanation: "It dynamically builds its pattern directory on the fly. <br><br>💡 **Real-Life Example:** Imagine two spies passing secret notes. Instead of having to carry a massive codebook from the start, they invent the secret codebook dynamically while they talk, learning it together." },
    { q: "The visible spectrum tells us that Violet light has the exact same wavelength size as Red light.", answer: "False", explanation: "Red light has a much longer, lazier wave. Violet has incredibly short rapid waves. <br><br>💡 **Real-Life Example:** Red light is like gentle ocean swells rolling in. Violet light is like chaotic, rapid ripples shaking the water." },
    { q: "An RGB coloured image in a computer requires three completely separate data matrices stacked on top of each other.", answer: "True", explanation: "A frame needs one 2D spatial grid for Red, Green, and Blue. <br><br>💡 **Real-Life Example:** Like old-school cartoon cell animation. Drawing the Red elements on one clear plastic sheet, Green on another, and Blue on a third, then laying them over each other to form the final frame." },
    { q: "Applying a smoothing filter (averaging pixels) acts as a low-pass filter to destroy high-frequency noise.", answer: "True", explanation: "Averaging softens sharp transitions, removing erratic spikes (noise). <br><br>💡 **Real-Life Example:** Listening to a noisy radio with lots of static (high frequency). Turning down the 'Treble' knob acts as a low-pass filter, muffling the sharp static so you can focus on the vocals." },
    { q: "If you stack Scaling, Translating, and Rotating matrix operations, you can do them in any random order and get the exact same image.", answer: "False", explanation: "Matrix multiplication is completely non-commutative (Order matters immensely). <br><br>💡 **Real-Life Example:** Example: 'Put on socks, then shoes.' If you reverse that order to 'Put on shoes, then socks', the final physical outcome is ludicrously different. Order dictates reality!" },
    { q: "Python executes all code identically, and white-space/indentation is purely for the programmer to read the code easier, like HTML.", answer: "False", explanation: "HTML ignores spaces. Python uses spaces as absolute law! <br><br>💡 **Real-Life Example:** Without exact spaces, Python crashes similar to a math equation lacking parentheses: is 5 * 2 + 10 equal to 20 or 60? Indentation is Python's parentheses." },
    { q: "Oculus Rift and FOVE headsets rely on Augmented Reality (AR) to overlay data on the real world.", answer: "False", explanation: "Rift and FOVE are Virtual Reality (VR) visors, which block the entire real world. <br><br>💡 **Real-Life Example:** AR is wearing Google Glass while walking down an actual street. VR is putting a cardboard box over your head and staring at a screen depicting Mars." },
    { q: "A TV CRT beam modulating its intensity simply means flipping the light beam 'On' or 'Off' fully, making it totally impossible to create grayscale shades.", answer: "False", explanation: "Modulating means it alters the intensity incrementally, allowing dim or bright shots depending on the math from the frame buffer. <br><br>💡 **Real-Life Example:** It isn't just a basic on/off light switch, it's a dimmer dial, allowing thousands of varying brightness levels." },
    { q: "Python list indices generally start counting uniformly at the number 1.", answer: "False", explanation: "In nearly all programming, lists start mathematically at 0. <br><br>💡 **Real-Life Example:** Think of an escalator. The ground floor where you step on is Level 0. Pushing '1' takes you up one full flight of stairs." }
  ],
  longAnswer: [
    { q: "Explain the visual and mathematical difference between a smoothing pass and a sharpening pass in image filtering. Use a real-life analogy.", answer: "A smoothing pass averages pixel intensities, lowering the bold difference between adjacent pixels resulting in a blur. A sharpening pass specifically isolates edges, amplifying the contrast between light and dark areas.", explanation: "💡 **Real-Life Example:** Smoothing is like taking a photo and looking at it through frosted shower glass; the sharp lines disappear. Sharpening is like taking a thin black pen and tracing heavily over every single edge of an object in a drawing to make it visually pop off the page." },
    { q: "What is generation loss, and why doesn't it occur when using a compressor like LZW or Huffman?", answer: "Generation loss is the progressive degradation of file quality when an asset is repeatedly compressed and decompressed using a lossy medium like JPEG. Because algorithms like LZW and Huffman are completely lossless string manipulators, the literal binary is perfectly preserved.", explanation: "💡 **Real-Life Example:** JPEG is like playing a massive game of 'Telephone' with a photo. Every time you save it and pass it on, the algorithm guesses and throws away details, changing the message. With Huffman/Lossless, it is like handing a locked briefcase to someone: the exact document survives untouched no matter how many times the briefcase is passed." },
    { q: "Why is 'Shearing' considered an affine transformation but 'Perspective Wrapping' or 'Convolution' is not?", answer: "An affine transformation by geometric definition must preserve points, planes, and most importantly, parallel lines. Shearing slants an image, but parallel lines survive.", explanation: "💡 **Real-Life Example:** Take a wooden picture frame without glass and push on the top corner. The frame leans diagonally (Shear). The vertical sides are now slanted, but they are STILL parallel to each other. 'Perspective wrapping' is like standing on a road looking into the distance; the sides of the road converge (aren't parallel anymore), breaking the Affine rule." },
    { q: "How did Raster Scan engineering limitations physically dictate how hardware Frame Buffers work?", answer: "Because hardware like CRTs literally painted the image as a singular linear sweeping beam matching the screen's phosphors row by row, the Frame Buffer was designed to be a continuous queue of values that dumped analog voltages translating exactly to brightness intensities on the tube face.", explanation: "💡 **Real-Life Example:** Imagine a machine rapidly painting a highway line from a moving truck. The paint reservoir (Frame Buffer) must push out the paint in a perfectly timed, continuous stream exactly matching the truck's speed (Raster sweep). If the reservoir hesitated, there would be a massive gap in the line." },
    { q: "How does the 'Huffman coding tree' explicitly guarantee a smaller file size over plaintext ASCII?", answer: "Standard ASCII statically assigns every single character 8 bits regardless of how often it appears. Huffman maps the most frequently occurring characters to incredibly short codes. Infrequent characters receive longer codes.", explanation: "💡 **Real-Life Example:** If you manage a warehouse, you put the items that sell 100 times a day (like 'E' or 'A') rigidly by the front loading dock (short 2-bit code) so you can fetch them instantly. Items that sell once a year (like 'Z') go in the deep back warehouse (long 8-bit code) because it doesn't waste much time overall." },
    { q: "Why did hardware evolve to use Frame Buffers instead of directly driving monitors from a computer's CPU?", answer: "A CRT monitor required an absolutely perfect, uninterrupted, incredibly fast stream of sequential pixel data to maintain stability without flickering. A computer CPU handles multiple random erratic tasks and cannot guarantee this constant focus.", explanation: "💡 **Real-Life Example:** A CPU is a chaotic manager solving 20 problems at once while answering the phone. The monitor is a conveyer belt that CANNOT stop. The manager builds the products and dumps them into a massive holding bin (Frame Buffer). The holding bin then smoothly and flawlessly feeds the conveyer belt without any interruptions from the manager." }
  ]
};
