const questionBank = {
  mcq: [
    { q: "What is the primary characteristic of Lossless Compression?", options: ["It uses Fourier Transformation", "Origin data is recreated with no data loss", "It eliminates unimportant data", "The resulting file is always larger"], answer: "Origin data is recreated with no data loss", explanation: "Lossless compression guarantees the original data can be reconstructed exactly, bit-for-bit, without losing any information.<br><br>💡 **Real-Life Example:** Imagine packing a suitcase. You fold your clothes perfectly (compress) to fit them all in. When you arrive at your hotel and unpack (decompress), every single piece of clothing is still there, exactly as it was. A ZIP file on your computer does exactly this." },
    { q: "Which algorithm is an example of Lossy Compression?", options: ["Run-Length Encoding (RLE)", "Huffman coding", "LZW algorithm", "JPEG compression"], answer: "JPEG compression", explanation: "JPEG compression drastically reduces image sizes by permanently destroying 'unimportant' visual data (usually high-frequency details) using complex math.<br><br>💡 **Real-Life Example:** It is like summarizing a 500-page book into a 10-page essay. The essay is much smaller and easier to carry, and you get the main idea of the story, but you can NEVER rebuild the exact original 500 pages from it. The extra details are lost forever." },
    { q: "If an original file is 200 KB and the compressed file is 50 KB, what is the compression ratio?", options: ["2:1", "4:1", "10:1", "5:1"], answer: "4:1", explanation: "Compression ratio is simply Original Size divided by Compressed Size (200 / 50 = 4).<br><br>💡 **Real-Life Example:** If you had a giant fluffy pillow (200 cubic inches) and you squished it down into a vacuum-seal bag until it was only 50 cubic inches, it is now 1/4th of its original size. The ratio is 4-to-1." },
    { q: "Which algorithm optimally encodes characters based on their frequency of occurrence?", options: ["LZW", "Huffman Coding", "RLE", "Fourier Transform"], answer: "Huffman Coding", explanation: "Huffman coding assigns very short binary codes to common letters (like 'E') and long binary codes to rare letters (like 'Z').<br><br>💡 **Real-Life Example:** Think of Morse Code. A very common letter like 'E' is just a single short dot ( . ). A rare letter like 'Q' is a long sequence ( --.- ). This ensures that the most common messages take the shortest amount of time to tap out." },
    { q: "What does LZW stand for (conceptually in class)?", options: ["Lempel-Ziv-Welch", "Light-Zone-Weight", "Lossless-Zero-Width", "Luminance-Z-Wave"], answer: "Lempel-Ziv-Welch", explanation: "Lempel-Ziv-Welch builds a dictionary of repeated patterns 'on the fly' as it compresses data.<br><br>💡 **Real-Life Example:** If you are texting a friend repeatedly about 'University of Northampton', it takes a long time to type. LZW mathematically figures out that phrase happens a lot, and assigns it an automatic shorthand like '!1'. Next time it sees 'University of Northampton', it just saves '!1', making the file tiny." },
    { q: "Visible light wavelength ranges from:", options: ["Infrared to Ultraviolet", "Red to Violet", "Green to Blue", "Cyan to Magenta"], answer: "Red to Violet", explanation: "Visible light in the electromagnetic spectrum stretches from Red (longer, lazy waves) to Violet (shorter, energetic waves).<br><br>💡 **Real-Life Example:** Look at a rainbow! It always starts with Red on the outside and ends with Violet on the inside. Everything else, like X-rays or Radio waves, is invisible to us." },
    { q: "How does the human eye perceive different colours?", options: ["Through two lenses", "Through rods only", "Through three types of cones", "Through cornea reflections"], answer: "Through three types of cones", explanation: "The eye has three types of receptors called cones; one prefers Red light, one prefers Green, and one prefers Blue.<br><br>💡 **Real-Life Example:** Think of your eye like a bucket of three different paints. By mixing just those three primary paints (red, green, blue cones firing off in your brain at different intensities), your brain invents every other colour you see, like yellow or purple." },
    { q: "Which properties typically define colour in computer graphics models?", options: ["Red, Orange, Yellow", "Hue, Saturation, and Luminance", "Bit, Byte, Nibble", "Vector, Raster, Pixel"], answer: "Hue, Saturation, and Luminance", explanation: "These properties describe colour intuitively. Hue is the base color, Saturation is the purity, and Luminance is the brightness.<br><br>💡 **Real-Life Example:** Imagine buying paint. 'Hue' is picking Red. 'Saturation' is choosing between a bright fire-engine Red or a faded, washed-out greyish-Red. 'Luminance' is whether you shine a bright flashlight on that paint (bright) or turn off the lights entirely (pitch black)." },
    { q: "In older Cathode Ray Tube (CRT) televisions, how was the picture scanned?", options: ["Vector scanning from center", "Raster Scan System", "Digital projection", "Quantum dots"], answer: "Raster Scan System", explanation: "The electron beam swept across the screen one row at a time, moving from left to right, and top to bottom.<br><br>💡 **Real-Life Example:** Think of reading a book or painting a fence. You read from left to right across the top line, then drop down and read the next line, left to right, all the way to the bottom. A CRT drew the picture the exact same way at blinding speed." },
    { q: "What hardware component holds the set of intensity values defining a CRT/monitor picture?", options: ["CPU Cache", "Hard Drive", "Frame buffer", "Sound Card"], answer: "Frame buffer", explanation: "Picture definition is stored in a specialised memory called a frame buffer before it reaches the screen.<br><br>💡 **Real-Life Example:** Think of a chef in a restaurant. The frame buffer is the 'waiter's tray'. The computer (chef) builds the complete picture and places it on the tray. Then, the tray (frame buffer) immediately carries it perfectly to the screen (customer) instantly." },
    { q: "What is the primary purpose of a smoothing spatial filter?", options: ["Sharpen edges", "Blur the image and reduce noise", "Change the image hue", "Compress the image size"], answer: "Blur the image and reduce noise", explanation: "Smoothing filters act as weighted averages, reducing sharp intensity transitions.<br><br>💡 **Real-Life Example:** Imagine a bumpy, rocky gravel road (image noise). A smoothing filter is like pouring hot asphalt over the gravel and rolling it flat. It removes the sharp bumps and makes everything locally blend together smoothly, but it makes the road blurrier to look at." },
    { q: "When modifying an edge pixel using a 3x3 filter, what is the 'Zero-Padding' solution?", options: ["Deleting the image", "Adding a border of zeroes around the image", "Multiplying by zero", "Setting all pixels to zero"], answer: "Adding a border of zeroes around the image", explanation: "Zero-padding adds a theoretical ring of 0s outside the image so the math can complete without crashing.<br><br>💡 **Real-Life Example:** Imagine you are laying 3x3 square tiles on a floor, but you reach the wall. Your tile hangs over the edge into empty space. Zero-Padding is like pretending there is invisible floor outside the house to temporarily support your tile so you can finish laying it." },
    { q: "What property does an affine transformation mathematically preserve?", options: ["Colour values", "Image file extension", "Parallel lines", "Pixel grouping"], answer: "Parallel lines", explanation: "An affine transformation is a linear mapping (Scaling, Translation, Shearing) that ensures sets of originally parallel lines never cross.<br><br>💡 **Real-Life Example:** Think of drawing a grid on a rubber sheet. If you pull the sheet sideways (shearing) or stretch it (scaling), the grid lines will slant or grow, but the lines that used to be parallel will *still* be parallel. They will never suddenly intersect." },
    { q: "In Python, which keyword is fundamentally used to define a new function?", options: ["func", "def", "function", "lambda"], answer: "def", explanation: "The 'def' keyword introduces a reusable function definition.<br><br>💡 **Real-Life Example:** Like naming a recipe! `def bake_cake():` tells the kitchen (Python) that whenever you yell 'bake_cake()', it needs to execute the specific baking instructions you typed inside that block." },
    { q: "If a JPEG image is continually compressed and decompressed multiple times, what happens?", options: ["Nothing, it is lossless", "Generation loss occurs due to cumulative data discarding", "File size increases automatically", "It converts to a PNG"], answer: "Generation loss occurs due to cumulative data discarding", explanation: "Lossy algorithms throw away detailed math every time they save. Resaving it repeatedly destroys it.<br><br>💡 **Real-Life Example:** Imagine photocopying a picture. Then you take that photocopy, and photocopy *it*. The third time, you photocopy that photocopy. Eventually, the picture turns into a blurry, blocky mess. That is exactly what happens if you repeatedly save a JPEG over and over." },
    { q: "Which of the following is an example of an immutable sequence in Python?", options: ["List", "Dictionary", "Set", "Tuple"], answer: "Tuple", explanation: "Once initialized, you cannot alter the size or contents of a standard Python tuple.<br><br>💡 **Real-Life Example:** A List `[]` is a whiteboard; you can erase things and draw new ones. A Tuple `()` is a tattoo; whatever you wrote when you created it is permanent and cannot be deleted or changed." },
    { q: "What mathematical operation is the foundation of applying a spatial filter kernel across an entire image?", options: ["Matrix Transpose", "Fourier Transform", "Convolution / Correlation", "Cross Product"], answer: "Convolution / Correlation", explanation: "Kernels are multiplying matrices placed over image matrices systematically.<br><br>💡 **Real-Life Example:** Think of having a small magnifying glass (your kernel) that changes the color of anything underneath it. You slide the magnifying glass across a giant map (the image) pixel by pixel, altering the map precisely as you move. This sliding math operation is convolution." },
    { q: "Which colour model is traditionally used for physical color printing?", options: ["RGB", "HSB", "CMYK", "YUV"], answer: "CMYK", explanation: "Cyan, Magenta, Yellow, and Key (Black) are subtractive colors used for ink.<br><br>💡 **Real-Life Example:** Monitors use light (RGB), which gets brighter the more you add. But on totally white paper, adding colored ink makes it *darker*. So physical printers use Cyan, Magenta, Yellow, and Black ink to filter light out of the white paper." },
    { q: "TCA EXAM: If you apply a 3x3 smoothing filter (where every weight is 1/9) to a 3x3 image block where every pixel currently has an intensity of 90, what is the new central pixel value?", options: ["10", "810", "90", "1/9"], answer: "90", explanation: "Calculated by: (90 * 1/9) + (90 * 1/9)... nine times. The sum is 90. <br><br>💡 **Real-Life Example:** The average height of a room where every single person is exactly 6 feet tall... is 6 feet." },
    { q: "TCA EXAM: When tracing the LZW compression algorithm on the string 'ina mina nami', what triggers LZW to physically add a new entry to its internal dictionary?", options: ["Seeing a single 'm' character", "Encountering any lowercase vowel", "Reading a string pattern it has not seen before in the sequence", "Calculating the bit-width of the entire paragraph"], answer: "Reading a string pattern it has not seen before in the sequence", explanation: "LZW's core mechanic is taking the 'current recognized pattern' plus the 'next unseen character' and adding that combination to the dictionary." },
    { q: "TCA EXAM: An image is 1920x1080 resolution running at 24-bit TrueColor. How large is the uncompressed frame in megabytes (MB) approximately?", options: ["2 MB", "6.2 MB", "20 MB", "62 MB"], answer: "6.2 MB", explanation: "1920 * 1080 = 2,073,600 pixels. 24-bit color = 3 Bytes per pixel. 2,073,600 * 3 = 6,220,800 Bytes, which is roughly 6.2 MB." },
    { q: "TCA EXAM: A string has the characters 'A' (100 times), 'B' (50 times), and 'C' (10 times). In a Huffman tree, which character will be placed furthest down the tree from the root?", options: ["A", "B", "C", "They are on the same level"], answer: "C", explanation: "Because 'C' is the rarest (10 times), Huffman forces it to the deepest part of the tree so it has the longest binary code, reserving shorter codes for 'A'." },
    { q: "TCA EXAM: Applying a 3x3 Sharpening filter usually has a central weight of what mathematical characteristic?", options: ["A very strong positive number (e.g., 8 or 9)", "A negative fraction (e.g., -1/9)", "Zero (0)", "A small positive fraction (e.g., 1/9)"], answer: "A very strong positive number (e.g., 8 or 9)", explanation: "Sharpening matrices usually have a strong positive center (like 8) surrounded by negative numbers (-1). This amplifies the central difference against its neighbours." },
    { q: "TCA EXAM: If a Python image matrix 'img' has shape (1080, 1920, 3), how many values must a loop iterate through to process every single R, G, and B number individually?", options: ["1080", "1920", "2073600", "6220800"], answer: "6220800", explanation: "You must multiply the dimensions: 1080 * 1920 * 3 = 6,220,800 individual intensity values." },
    { q: "TCA EXAM: LZW dictionary indices conventionally start above 255. Why?", options: ["To leave room for negative numbers", "Because the first 0-255 slots are pre-filled with the standard ASCII character set", "Because LZW only works on 16-bit systems", "Math logic requires starting at 256"], answer: "Because the first 0-255 slots are pre-filled with the standard ASCII character set", explanation: "The base dictionary must know every single base letter natively. When LZW finds a new two-letter combo, it assigns it index 256, then 257, etc." },
    { q: "TCA EXAM: A 256x256 monochrome (8-bit grayscale) image requires exactly how many kilobytes (KB) of memory?", options: ["8 KB", "64 KB", "256 KB", "1024 KB"], answer: "64 KB", explanation: "256 * 256 = 65,536 pixels. At 8 bits (1 byte) each, that's exactly 65,536 bytes. Divided by 1024 = 64 KB." },
    { q: "TCA EXAM: You have a starting coordinate vector [x=10, y=20, 1] and you apply an Affine Scaling matrix of Sx=2, Sy=3. What is the new coordinate?", options: ["x=20, y=60", "x=12, y=23", "x=5, y=6.6", "x=30, y=10"], answer: "x=20, y=60", explanation: "Scaling directly multiplies: 10 * 2 = 20 for X. 20 * 3 = 60 for Y. Translation remains untouched." },
    { q: "TCA EXAM: If Run-Length Encoding (RLE) is applied to the string 'AABBCC', the output is '2A2B2C'. Did it successfully 'compress' the file size?", options: ["Yes, massive reduction", "No, it stayed exactly the same size", "No, it increased the size vastly", "Yes, it halved the size"], answer: "No, it stayed exactly the same size", explanation: "'AABBCC' is 6 characters. '2A2B2C' is 6 characters. Compression ratio is exactly 1:1. RLE fails on short sequences." },
    { q: "TCA EXAM: When multiplying [10, 10, 1] by an Affine Translation matrix with Tx=5, Ty=-5, what is the resulting position?", options: ["50, -50", "15, 5", "5, 15", "10, 10"], answer: "15, 5", explanation: "Translation matrices mathematically ADD to the original coordinates. 10+5 = 15. 10-5 = 5." },
    { q: "TCA EXAM: In standard Python Numpy, image slicing to crop the center 100x100 of a 500x500 image looks like what?", options: ["img[200:300, 200:300]", "img.crop(200, 300)", "img[200-300][200-300]", "img[CENTER:100]"], answer: "img[200:300, 200:300]", explanation: "Array slicing defines [startRow:endRow, startCol:endCol]. 200 to 300 leaves exactly 100 pixels." },
    { q: "TCA EXAM: Applying Convolution, you have a 3x3 pixel area where all values are '255' (pure white). You apply a smoothing filter of all '1/9's. What is the new center pixel?", options: ["255 (Pure White)", "0 (Pure Black)", "128 (Gray)", "9 (Dark Gray)"], answer: "255 (Pure White)", explanation: "Nine 255s each multiplied by 1/9 equals nine 28.3s. Added together safely equals 255. Flat zones are untouched by smoothing!" },
    { q: "TCA EXAM: The 'Quantization Table' step in JPEG compression specifically does what mathematical action?", options: ["Changes colors to CMYK", "Divides the complex Cosine frequency numbers and rounds them down to zero if they are small", "Multiplies everything by 255", "Inverts the matrix"], answer: "Divides the Cosine frequency numbers and rounds them down to zero if they are small", explanation: "Quantization physically truncates and floors delicate high-frequency coefficients to 0 so they can be squashed via RLE." }
  ],
  fillInTheBlank: [
    { q: "Compression is the process of transforming ______ data to a compressed format.", answer: "raw", explanation: "Compression converts bulky unoptimized data into efficiently encoded data.<br><br>💡 **Real-Life Example:** Taking all your loose 'raw' clothes scattered in the bedroom and tightly folding them into a suitcase." },
    { q: "A compression method is considered ______ if the exact original data can be 100% recovered without fail.", answer: "lossless", explanation: "Lossless means zero original bits are permanently altered. <br><br>💡 **Real-Life Example:** A ZIP file wrapping a word document. If the ZIP lost a single letter, the document would be ruined." },
    { q: "______ is an example of a simple algorithm that counts consecutive repeated identical characters natively.", answer: "RLE", explanation: "Run-Length Encoding compresses 'AAAABBB' into '4A3B'. <br><br>💡 **Real-Life Example:** Saying 'I have 5 apples' is much faster than saying 'I have an apple, an apple, an apple, an apple, and an apple'." },
    { q: "In a CRT screen, the picture is drawn by firing an ______ beam at the front glass.", answer: "electron", explanation: "The TV blasts electrons at phosphors which light up. <br><br>💡 **Real-Life Example:** Like turning on a garden hose and spraying water back and forth across a dirty wall to clean a specific shape." },
    { q: "The pattern of moving from left-to-right, row-by-row top-to-bottom is known as a ______ scan system.", answer: "raster", explanation: "Raster scanning was how old displays updated entirely uniformly. <br><br>💡 **Real-Life Example:** Like a lawnmower cutting a massive field by making continuous straight horizontal sweeps across the grass, dropping down slightly each pass." },
    { q: "In the human eye, biological sensors called ______ are primarily responsible for perceiving bright colour.", answer: "cones", explanation: "Cones handle Red/Green/Blue, while Rods handle dim grayscale light. <br><br>💡 **Real-Life Example:** Think of cones as high-definition expensive daylight cameras, and rods as cheap blurry night-vision cameras." },
    { q: "Hue, Saturation, and ______ are three main properties of colour commonly separated in computer graphics.", answer: "luminance", explanation: "Luminance represents the brightness of the pixel decoupled from its actual Hue. <br><br>💡 **Real-Life Example:** Luminance is like adjusting the dimmer switch on your lightbulb. The red wall is still exactly 'Red' (Hue), but turning the dial changes how bright it is (Luminance)." },
    { q: "Applying a weighted 3x3 averaging filter matrix to an image will visually ______ it.", answer: "blur", explanation: "Averaging local neighbourhoods acts as a low-pass filter, flattening sharp changes. <br><br>💡 **Real-Life Example:** If you take a sharp photograph and rub your thumb aggressively across the wet ink, you mix the sharp colors together, creating a soft blur." },
    { q: "A linear math mapping method that guarantees previously parallel lines remain parallel is called an ______ transformation.", answer: "affine", explanation: "Affine geometry allows scaling, shearing, rotating, and translating. <br><br>💡 **Real-Life Example:** Drawing two parallel train tracks on the side of a balloon. No matter how much you inflate (scale) the balloon, those tracks will stretch but never cross." },
    { q: "In Python, ______ are mandatory structural tools used to outline which code blocks belong to `if` statements.", answer: "indentation", explanation: "Python relies on spaces instead of `{}` brackets. <br><br>💡 **Real-Life Example:** In a grocery list, you visually indent 'Apples' and 'Oranges' under the heading 'Fruit' so you know they belong there. Python uses this visual rule to actually run the program." },
    { q: "Unlike lists, Python ______ use parentheses `()` and their data cannot be changed safely after creation.", answer: "tuples", explanation: "Tuples are immutable locked collections. <br><br>💡 **Real-Life Example:** Setting the dimensions of your TV screen (1920, 1080). You never want a math error to accidentally change your physical TV width to 5, so you use a protective Tuple." },
    { q: "To perform matrix operations incredibly fast on an OpenCV image, one heavily uses the ______ math library in Python.", answer: "numpy", explanation: "Numpy overrides Python's slow loops with lightning-fast C-code backgrounds. <br><br>💡 **Real-Life Example:** Trying to do complex math by hand (pure Python) versus handing the math to an automated supercomputer calculator (Numpy)." },
    { q: "Translating an image mathematically shifts its pixels along the _ and _ axes linearly.", answer: "x and y", explanation: "Translation moves geometry around the frame. <br><br>💡 **Real-Life Example:** Playing chess. Moving a pawn from square D2 to D4 doesn't rotate or shrink the pawn; it simply alters its X,Y grid coordinates." },
    { q: "An image represented by a mathematical formula (lines and curves) rather than a grid of physical pixels is called a ______ graphic.", answer: "vector", explanation: "Vectors are math, allowing infinite zooming. <br><br>💡 **Real-Life Example:** Imagine taking a tiny photo and zooming in until it looks like blocky Lego (Raster/Bitmap). Vector graphics are like a rubber band pulled between two nails; if you walk backward, it scales infinitely without ever looking blocky." },
    { q: "TCA EXAM: When manually calculating spatial correlation for a 3x3 image neighborhood, the new brightness value is purely the ______ of each (Pixel x Weight) product.", answer: "sum", explanation: "The central pixel becomes the accumulated sum of the 9 weighted multiplications." },
    { q: "TCA EXAM: Before Huffman Encoding mathematically guarantees the shortest possible bit-lengths, it must first calculate the exact ______ of every single character in the document.", answer: "frequency", explanation: "A probability map (or frequency count) is mandatory to build the tree. Frequent letters get shorter branches." },
    { q: "TCA EXAM: If you have a 10x10 image and you drop the outer 1 pixel edge completely because you don't want to use zero-padding, the new output image shape is _ x _.", answer: "8x8", explanation: "10 minus 1 on the top and 1 on the bottom leaves 8. 10 minus 1 on the left and 1 on the right leaves 8." },
    { q: "TCA EXAM: A 4K display is 3840x2160 pixels. At 24-bit color depth, a single uncompressed frame takes approximately ______ Megabytes of Frame Buffer memory.", answer: "24", explanation: "3840 * 2160 = 8.29 million pixels. At 3 Bytes/pixel, that is ~24,883,200 Bytes or roughly 24 MB." },
    { q: "TCA EXAM: LZW compression operates effectively because its dictionary is built ______, matching the decoding process without transferring the table.", answer: "dynamically", explanation: "LZW predicts and adds dictionary codes on-the-fly, the mathematical mirror of decompression." },
    { q: "TCA EXAM: In Affine Transformations, applying a Translation matrix mathematically means doing ______ arithmetic to the X/Y coordinates.", answer: "addition", explanation: "Scaling/Shearing uses multiplication. Translation strictly uses matrix Addition." },
    { q: "TCA EXAM: RLE on the sequence 'X X Y Y Z Z Z' results in the sequence ______.", answer: "2X2Y3Z", explanation: "RLE counts the duplicates and places the integer before the literal character." },
    { q: "TCA EXAM: Spatial Filtering relies heavily on ______ operations, meaning the math uses the block of pixels intimately touching the target pixel.", answer: "neighbourhood", explanation: "Instead of 'Point' arithmetic (isolated), it is 'Neighbourhood' arithmetic (contextual)." },
    { q: "TCA EXAM: Huffman mapping guarantees that if 'A' is 60% of the document and 'Z' is 1%, 'A' will be placed structurally much closer to the ______ of the branching tree.", answer: "root", explanation: "Near the root/top means only 1 or 2 binary decisions (bits) are needed to reach it." },
    { q: "TCA EXAM: When multiplying matrices, rotating by 90 degrees then translating 10 pixels right yields a radically different result than translating 10 right then rotating 90 because matrices are non-______.", answer: "commutative", explanation: "A x B does NOT equal B x A in matrix algebra." },
    { q: "TCA EXAM: The term ______ error occurs when rounding fractional pixel coordinates to integers, causing jagged lines or artifacting.", answer: "quantization", explanation: "A true pixel cannot exist at (5.3, 10.7), so flooring it to (5,10) creates structural error known as quantization or aliasing." },
    { q: "TCA EXAM: If a 50x50 monochrome pixel array has all 2,500 intensity values set to '0', the screen will visually render completely ______.", answer: "black", explanation: "In 8-bit mapping, 0 is definitively Black (no light), and 255 is pure White (maximum light)." },
    { q: "TCA EXAM: Because an 'RGB' TV natively understands Red/Green/Blue natively, converting a YUV (Luminance/Chrominance) broadcast signal back to RGB natively inside the TV requires rapid ______ multiplication.", answer: "matrix", explanation: "YUV mathematically maps back to RGB via a fixed affine-like color matrix conversion on the hardware chip." }
  ],
  matchFollowing: [
    {
      q: "Match the following compression tools to their real-life analogies",
      pairs: [
        { left: "Lossless Compression", right: "Packing a parachute perfectly so it opens safely" },
        { left: "Lossy Compression", right: "Trimming a novel down to a Wikipedia summary" },
        { left: "Huffman Encoding", right: "Using Morse Code for frequent letters" },
        { left: "Run Length Encoding (RLE)", right: "Saying 'Five Apples' instead of 'Apple Apple Apple Apple Apple'" }
      ],
      explanation: "💡 Connecting complex math algorithms to everyday actions makes them obvious. Lossy destroys data (like summarizing a book). Lossless preserves exactly everything."
    },
    {
      q: "Match the TV/Screen terms to their real-life actions",
      pairs: [
        { left: "Raster Scan", right: "Painting a wall row-by-row, top to bottom" },
        { left: "Refresh Rate", right: "Flipping through a flipbook of drawings rapidly" },
        { left: "Monochrome Display", right: "Watching an old black and white TV" },
        { left: "Frame Buffer Memory", right: "A waiter holding the chef's finished plate, ready for the customer" }
      ],
      explanation: "💡 Monitors are just extremely fast analogue/digital converters tricking your eyes using grids."
    },
    {
      q: "Match the Spatial Filtering concepts to physical actions",
      pairs: [
        { left: "Smoothing Filter", right: "Rubbing your thumb over wet ink to blend it" },
        { left: "Sharpening Filter", right: "Tracing the edges of a shape with a dark marker" },
        { left: "Zero-padding edge fix", right: "Pretending there are black invisible pixels outside the photo" },
        { left: "Convolution Matrix Math", right: "Sliding a colour-changing magnifying glass across a map" }
      ],
      explanation: "💡 Filtering doesn't 'know' what the picture is, it just runs blind math blindly sliding across the pixels."
    },
    {
      q: "Match the Python structures to real-life equivalents",
      pairs: [
        { left: "List [ ]", right: "A whiteboard list where you can constantly erase and add items" },
        { left: "Tuple ( )", right: "A tattoo. Once written, it can never be changed" },
        { left: "Indentation", right: "Formatting a grocery list with indented sub-categories" },
        { left: "OpenCV Library", right: "A pre-built heavy factory that processes images for you" }
      ],
      explanation: "💡 Python is fundamentally built to be readable and logical, mimicking human reasoning patterns through structures like Lists and Indentations."
    },
    {
      q: "TCA EXAM: Match the algorithmic tracing process to the compression method",
      pairs: [
        { left: "Requires building a Probability Tree", right: "Huffman Encoding" },
        { left: "Builds a Dictionary dynamically using Previous + Next String", right: "LZW Encoding" },
        { left: "Fails disastrously to compress non-repeating random data like 'A B C D E F'", right: "Run Length Encoding (RLE)" },
        { left: "Eliminates high-frequency data using Cosine math", right: "JPEG Compression" }
      ],
      explanation: "💡 Identifying the core computational mechanism is critical for the TCA."
    },
    {
      q: "TCA EXAM: Match 3x3 Spatial Calculation conditions",
      pairs: [
        { left: "All kernel weights sum exactly to 1.0", right: "Prevents the overall image brightness from changing" },
        { left: "Kernel uses a negative outer ring (-1) and strong positive center (8)", right: "Highlights sharp edge differences (Sharpening)" },
        { left: "Zero-padding applied to the corner pixel", right: "Forces 5 mathematical multiplications to hit 0" },
        { left: "Edge Replication applied to edge pixel", right: "Uses the exact border value natively as a fake neighbour" }
      ],
      explanation: "💡 Recognizing filter formulas mathematically prepares you for raw calculation trace questions."
    },
    {
      q: "TCA EXAM: Match Affine Calculation Rules",
      pairs: [
        { left: "Matrix Size required to multiply [X,Y,1]", right: "3x3 Matrix grid" },
        { left: "Scaling matrix with Sx=1, Sy=1", right: "Identity Matrix (No visual change)" },
        { left: "Shearing matrix", right: "Alters X based on Y's current height, maintaining parallel lines" },
        { left: "Rotation matrix", right: "Heavy utilization of Sine and Cosine variables" }
      ],
      explanation: "💡 Core math properties dictating pixel geometry."
    },
    {
      q: "TCA EXAM: Math logic matching for Memory and Bits",
      pairs: [
        { left: "24-bit TrueColor", right: "16.7 Million unique possible color combinations" },
        { left: "1-bit Monochrome", right: "Exactly 2 colors: Black and White" },
        { left: "8-bit Grayscale", right: "256 shades of grey" },
        { left: "M x N dimensions", right: "Width multiplied by Height mapping the total raw Pixel Count" }
      ],
      explanation: "💡 Calculating sizes requires knowing the exact Byte constraints behind the bits."
    }
  ],
  trueFalse: [
    { q: "A compression ratio of 2:1 means the compressed file is half the size of the original.", answer: "True", explanation: "Original (2) divided by Compressed (1) = 2. <br><br>💡 **Real-Life Example:** Squeezing a massive sleeping bag into a tiny stuff sack that takes up exactly half the space in your hiking bag." },
    { q: "JPEG uses math like 'Discrete Cosine Transforms' to permanently throw away visual data, making it a lossy format.", answer: "True", explanation: "JPEG isolates high-frequency pixels and discards them because our brains don't notice. <br><br>💡 **Real-Life Example:** Stripping the extremely high-pitched sounds out of an MP3 song because humans can only hear up to a certain pitch anyway." },
    { q: "If you tilt an image so its sides slant (Shearing), the straight sides become warped and wavy like a funhouse mirror.", answer: "False", explanation: "Shearing maintains perfectly straight parallel lines. <br><br>💡 **Real-Life Example:** Pushing on the side of a deck of playing cards. The deck tilts diagonally, but the sides remain perfectly smooth and straight, never wavy." },
    { q: "LZW compression doesn't require an enormous dictionary attached to the file because it logically re-builds the dictionary while you unzip it.", answer: "True", explanation: "It dynamically builds its pattern directory on the fly. <br><br>💡 **Real-Life Example:** Imagine two spies passing secret notes. Instead of having to carry a massive codebook from the start, they invent the secret codebook dynamically while they talk, learning it together." },
    { q: "The visible spectrum tells us that Violet light has the exact same wavelength size as Red light.", answer: "False", explanation: "Red light has a much longer, lazier wave. Violet has incredibly short rapid waves. <br><br>💡 **Real-Life Example:** Red light is like gentle ocean swells rolling in. Violet light is like chaotic, rapid ripples shaking the water." },
    { q: "An RGB coloured image in a computer requires three completely separate data matrices stacked on top of each other.", answer: "True", explanation: "A frame needs one 2D spatial grid for Red, Green, and Blue. <br><br>💡 **Real-Life Example:** Like old-school cartoon cell animation. Drawing the Red elements on one clear plastic sheet, Green on another, and Blue on a third, then laying them over each other to form the final frame." },
    { q: "Applying a smoothing filter (averaging pixels) acts as a low-pass filter to destroy high-frequency noise.", answer: "True", explanation: "Averaging softens sharp transitions, removing erratic spikes (noise). <br><br>💡 **Real-Life Example:** Listening to a noisy radio with lots of static (high frequency). Turning down the 'Treble' knob acts as a low-pass filter, muffling the sharp static so you can focus on the vocals." },
    { q: "If you stack Scaling, Translating, and Rotating matrix operations, you can do them in any random order and get the exact same image.", answer: "False", explanation: "Matrix multiplication is completely non-commutative (Order matters immensely). <br><br>💡 **Real-Life Example:** Example: 'Put on socks, then shoes.' If you reverse that order to 'Put on shoes, then socks', the final physical outcome is ludicrously different. Order dictates reality!" },
    { q: "Python executes all code identically, and white-space/indentation is purely for the programmer to read the code easier, like HTML.", answer: "False", explanation: "HTML ignores spaces. Python uses spaces as absolute law! <br><br>💡 **Real-Life Example:** Without exact spaces, Python crashes similar to a math equation lacking parentheses: is 5 * 2 + 10 equal to 20 or 60? Indentation is Python's parentheses." },
    { q: "Oculus Rift and FOVE headsets rely on Augmented Reality (AR) to overlay data on the real world.", answer: "False", explanation: "Rift and FOVE are Virtual Reality (VR) visors, which block the entire real world. <br><br>💡 **Real-Life Example:** AR is wearing Google Glass while walking down an actual street. VR is putting a cardboard box over your head and staring at a screen depicting Mars." },
    { q: "A TV CRT beam modulating its intensity simply means flipping the light beam 'On' or 'Off' fully, making it totally impossible to create grayscale shades.", answer: "False", explanation: "Modulating means it alters the intensity incrementally, allowing dim or bright shots depending on the math from the frame buffer. <br><br>💡 **Real-Life Example:** It isn't just a basic on/off light switch, it's a dimmer dial, allowing thousands of varying brightness levels." },
    { q: "Python list indices generally start counting uniformly at the number 1.", answer: "False", explanation: "In nearly all programming, lists start mathematically at 0. <br><br>💡 **Real-Life Example:** Think of an escalator. The ground floor where you step on is Level 0. Pushing '1' takes you up one full flight of stairs." },
    { q: "TCA EXAM: In Huffman coding, allocating a 1-bit code to a character that only appears once, and an 8-bit code to a character that appears 100 times, will yield widespread optimal compression.", answer: "False", explanation: "That is the exact opposite of Huffman logic! You MUST give the 1-bit code to the incredibly frequent item to save space." },
    { q: "TCA EXAM: When implementing Edge Padding via Zero-Padding mathematically on a corner pixel of an image, 5 out of the 9 filter mask weights will multiply against 0s.", answer: "True", explanation: "If you place a 3x3 center over the top-left corner (0,0), the top row (3 weights) and left column (additional 2 weights) hang out into the 'zero gap'. 5 total weights strike zeroes." },
    { q: "TCA EXAM: A Convolution operation using a 3x3 kernel over a 100x100 image requires roughly 90,000 individual multiplication actions.", answer: "True", explanation: "For everyone of the 10,000 pixels (100x100), you must perform 9 multiplication steps (for the 3x3 kernel). 10,000 x 9 = 90,000 math operations." },
    { q: "TCA EXAM: If a computer uses an 8-bit frame buffer memory, the maximum brightness intensity the raster scan can demand is mathematically 256.", answer: "False", explanation: "The maximum value is 255 because 8 bits provides 256 values total, counting 0. Valid numbers are 0 through 255." },
    { q: "TCA EXAM: If the Huffman algorithm determines that 'X' has a 90% probability and 'YZ' have 5% probability each, 'X' will mathematically be assigned a binary code at least 3 bits long.", answer: "False", explanation: "If 'X' is 90% probable, Huffman will assign it the absolute shortest code possible, guaranteeing a 1-bit code (like '0')." },
    { q: "TCA EXAM: Adding a Translation Affine matrix [Tx=50, Ty=100] to an image that was just Scaled down by [Sx=0.5, Sy=0.5] produces the identical mathematical result as Translating first, then Scaling.", answer: "False", explanation: "Matrix operations are non-commutative. Translating by 100 then scaling by 0.5 means the final physical offset is only 50 pixels! Doing it the other way means the physical offset remains a full 100 pixels." },
    { q: "TCA EXAM: Python handles a 3-Dimensional nested Array index lookup internally by multiplying the requested X/Y/Z indexes against the flattened C-memory byte strides perfectly.", answer: "True", explanation: "Underneath the syntax of img[X][Y], Numpy mathematically skips bytes in standard RAM memory by calculating: (Y * width_stride) + (X * color_stride)." },
    { q: "TCA EXAM: If RLE attempts to compress 'A B C D E F', the resulting string memory jumps from 6 Bytes to 12 Bytes, exhibiting negative compression capability.", answer: "True", explanation: "RLE outputs the count then the letter. '1A 1B 1C 1D 1E 1F'. This is 12 characters, completely doubling the file size." },
    { q: "TCA EXAM: LZW compression assigns the first unrecognised string combination to index #0.", answer: "False", explanation: "Indices 0 through 255 are strictly reserved for perfectly known single-byte ASCII characters. The first unrecognised two-letter combo gets assigned #256." },
    { q: "TCA EXAM: An identity matrix (containing purely 1s down its diagonal) applied to coordinate [150, 75, 1] returns exactly [150, 75, 1].", answer: "True", explanation: "The matrix math natively preserves the X and Y without any multipliers interfering, resulting in identical geometry." },
    { q: "TCA EXAM: Applying a smoothing filter to an image that has already been completely smoothed 10 times will mathematically result in absolutely no change on the 11th pass.", answer: "False", explanation: "Smoothing averages local pixels. Each consecutive pass will progressively pull distant bright/dark areas closer to median gray, continually increasing the blur. The math never fully stops pulling until the entire image is one solid block of grey." },
    { q: "TCA EXAM: Lossy JPEG Quantization mathematically divides a high-frequency block coefficient (e.g. 15.3) by a large quality parameter (e.g. 20), flooring the result (15.3/20 = 0.76 -> 0).", answer: "True", explanation: "By dividing and dropping the fraction, detailed high-frequency math simply becomes 0's, which are effortlessly wiped out by RLE packing." }
  ],
  longAnswer: [
    { q: "Explain the visual and mathematical difference between a smoothing pass and a sharpening pass in image filtering. Use a real-life analogy.", answer: "A smoothing pass averages pixel intensities, lowering the bold difference between adjacent pixels resulting in a blur. A sharpening pass specifically isolates edges, amplifying the contrast between light and dark areas.", explanation: "💡 **Real-Life Example:** Smoothing is like taking a photo and looking at it through frosted shower glass; the sharp lines disappear. Sharpening is like taking a thin black pen and tracing heavily over every single edge of an object in a drawing to make it visually pop off the page." },
    { q: "What is generation loss, and why doesn't it occur when using a compressor like LZW or Huffman?", answer: "Generation loss is the progressive degradation of file quality when an asset is repeatedly compressed and decompressed using a lossy medium like JPEG. Because algorithms like LZW and Huffman are completely lossless string manipulators, the literal binary is perfectly preserved.", explanation: "💡 **Real-Life Example:** JPEG is like playing a massive game of 'Telephone' with a photo. Every time you save it and pass it on, the algorithm guesses and throws away details, changing the message. With Huffman/Lossless, it is like handing a locked briefcase to someone: the exact document survives untouched no matter how many times the briefcase is passed." },
    { q: "Why is 'Shearing' considered an affine transformation but 'Perspective Wrapping' or 'Convolution' is not?", answer: "An affine transformation by geometric definition must preserve points, planes, and most importantly, parallel lines. Shearing slants an image, but parallel lines survive.", explanation: "💡 **Real-Life Example:** Take a wooden picture frame without glass and push on the top corner. The frame leans diagonally (Shear). The vertical sides are now slanted, but they are STILL parallel to each other. 'Perspective wrapping' is like standing on a road looking into the distance; the sides of the road converge (aren't parallel anymore), breaking the Affine rule." },
    { q: "How did Raster Scan engineering limitations physically dictate how hardware Frame Buffers work?", answer: "Because hardware like CRTs literally painted the image as a singular linear sweeping beam matching the screen's phosphors row by row, the Frame Buffer was designed to be a continuous queue of values that dumped analog voltages translating exactly to brightness intensities on the tube face.", explanation: "💡 **Real-Life Example:** Imagine a machine rapidly painting a highway line from a moving truck. The paint reservoir (Frame Buffer) must push out the paint in a perfectly timed, continuous stream exactly matching the truck's speed (Raster sweep). If the reservoir hesitated, there would be a massive gap in the line." },
    { q: "How does the 'Huffman coding tree' explicitly guarantee a smaller file size over plaintext ASCII?", answer: "Standard ASCII statically assigns every single character 8 bits regardless of how often it appears. Huffman maps the most frequently occurring characters to incredibly short codes. Infrequent characters receive longer codes.", explanation: "💡 **Real-Life Example:** If you manage a warehouse, you put the items that sell 100 times a day (like 'E' or 'A') rigidly by the front loading dock (short 2-bit code) so you can fetch them instantly. Items that sell once a year (like 'Z') go in the deep back warehouse (long 8-bit code) because it doesn't waste much time overall." },
    { q: "Why did hardware evolve to use Frame Buffers instead of directly driving monitors from a computer's CPU?", answer: "A CRT monitor required an absolutely perfect, uninterrupted, incredibly fast stream of sequential pixel data to maintain stability without flickering. A computer CPU handles multiple random erratic tasks and cannot guarantee this constant focus.", explanation: "💡 **Real-Life Example:** A CPU is a chaotic manager solving 20 problems at once while answering the phone. The monitor is a conveyer belt that CANNOT stop. The manager builds the products and dumps them into a massive holding bin (Frame Buffer). The holding bin then smoothly and flawlessly feeds the conveyer belt without any interruptions from the manager." },
    { q: "TCA EXAM: Demonstrate mathematically how the central brightness value of a 3x3 neighborhood is updated via spatial correlation applying filter weights.", answer: "Step 1: Overlay the 3x3 Kernel filter mask directly over the 3x3 pixel grid. Step 2: Multiply each of the nine local pixel values by its corresponding direct-overlap kernel weight. Step 3: Add all nine of the resulting products together. Step 4: The total summation becomes the stark new value for the central pixel, destroying its original independent brightness value.", explanation: "💡 **Real-Life Example:** This describes calculating a 'Weighted Average'. If your final grade is 90% test and 10% homework, you multiply your TestScore by 0.9 and Homework by 0.1, then add them. Kernels do this identically using spatial pixels instead of homework points." },
    { q: "TCA EXAM: Outline the core logical failure of Huffman Encoding when confronted with attempting to compress incredibly short strings (e.g. 'HELLO').", answer: "Huffman encoding mathematically optimizes the bit-length of characters, succeeding in reducing the string data payload itself. However, to correctly decode the file later, the specific Huffman 'Tree/Dictionary' map must be appended physically to the output file. For a tiny 5-letter word, the data overhead required to save the Dictionary structure is vastly larger than the couple of bytes saved by compressing the word, ultimately resulting in an inflated file size.", explanation: "💡 **Real-Life Example:** Imagine writing a 3-word secret letter. Trying to compress it by also sending an enormous 5-page 'decoder rulebook' completely defeats the purpose of saving cargo weight." },
    { q: "TCA EXAM: Calculate the memory size in Megabytes of Uncompressed Video that runs at 1920x1080, 24-bit TrueColor, at 60 fps for exactly 10 seconds.", answer: "Pixels per frame = 1920 * 1080 = 2,073,600. Bytes per frame = 2,073,600 * 3 = 6,220,800 Bytes (approx 6.22 MB/frame). Frames in 10 seconds = 60 * 10 = 600 frames. Total Memory = 6.22 MB/frame * 600 frames = 3,732.48 MB (or approx 3.7 Gigabytes).", explanation: "💡 **Calculation Logic:** Always establish the base Byte size of a single frame first. Then multiply by Framerate. Then multiply by Time." },
    { q: "TCA EXAM: Prove mathematically why matrix multiplication for Translation and Scaling is Non-Commutative by demonstrating doing it in reverse formats using Coordinate X=10.", answer: "Let Scale = 2. Let Translate = 5. Strategy 1 (Translate then Scale): Add 5 to 10 = 15. Then multiply by 2 = 30. Final Coordinate X=30. Strategy 2 (Scale then Translate): Multiply 10 by 2 = 20. Then add 5 = 25. Final Coordinate X=25. Because 30 != 25, the order dictates completely different spatial placement.", explanation: "💡 **Key Factor:** This mathematical rule forces graphics programmers to enforce rigid pipelines (usually Scale -> Rotate -> Translate) to ensure logical 3D positioning." },
    { q: "TCA EXAM: Hand-trace the theoretical first 3 steps of a LZW compression pass on the string 'ABABA'. What does the dictionary record dynamically?", answer: "1. Read 'A' (recognized as ASCII #65), read 'B' (next char). Combo 'AB' is not in dictionary. Output 65, add 'AB' to dictionary as #256. 2. Buffer moves to 'B'. Next char is 'A'. Combo 'BA' is not in dictionary. Output 66, add 'BA' as #257. 3. Buffer moves to 'A'. Next char is 'B'. Combo 'AB' IS magically in the dictionary now! Output the new code #256.", explanation: "💡 **Core Tracing Mechanic:** Always combine the matching buffer with the immediately following unseen letter. That pairing becomes your new entry." },
    { q: "TCA EXAM: Detail exactly why adopting 'Edge Replication' requires extra Python logic (if/else loops) when sliding a 3x3 kernel, compared to standard 'Zero-Padding'.", answer: "Zero padding simply involves generating a fake matrix permanently wrapped in a shell of 0's initially, allowing the identical generic mathematical filter sliding loop to safely run everywhere blindly. Edge Replication forces the logic to dynamically check 'Am I at an edge?' at every step and write specific variable code like `if x==0: value = img[0, y]` to dynamically fetch the nearest legitimate literal border value over and over. This 'If/Else' logic severely slows down processing.", explanation: "💡 **Algorithm Speed Test:** Any 'If/Else' check inside a 2-million-pixel loop mathematically paralyzes processing speed compared to blind multiplication on padded zeroes." },
    { q: "TCA EXAM: Contrast exactly how a Lossy compression algorithm (JPEG) handles high-frequency data versus low-frequency data via the DCT matrices.", answer: "Low-frequency data (gradual color shifts like the blue sky) is mathematically encoded very carefully with high precision weights in the upper-left of a DCT matrix grid ensuring it looks smooth to the human eye. High frequencies (sharp erratic changes) are shoved to the bottom-right of the DCT table and viciously hammered mathematically by the Quantization table dividing them down to 0, permanently destroying those rapid details because our biology struggles to see them anyway.", explanation: "💡 **Biological Hardware Exploit:** Lossy coding works purely because our hardware (retina cones) is flawed and easily tricked." },
    { q: "TCA EXAM: A Convolution spatial filter usually limits its mask weights fractionally so the sum equals 1.0 (e.g. nine 1/9 blocks). What happens visually and mathematically if the sum accidentally equals 1.5?", answer: "If the 3x3 filter weights sum to 1.5, the math forces each final pixel calculation to be artificially inflated by 50%. While it might still successfully 'blur' or 'sharpen' the image layout, every single pixel's luminance will fundamentally increase. The entire image will universally shift blindingly bright, rapidly 'blowing out' pure white (hitting the 255 ceiling) and destroying color definition.", explanation: "💡 **Filter Normalization Rule:** Keeping the matrix sum identical to 1.0 ensures identical total light emission." }
  ]
};
