const questionBank = {
  practice: [
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"A dynamic dictionary-based compressor that naturally discovers and records repeating string fragments on the fly.\"","options":["Spatial Filtering","Run-Length Encoding","Zero Padding","LZW Algorithm"],"answer":"LZW Algorithm","explanation":"LZW dynamically builds a dictionary as it scans input—each new repeated pattern gets a shorter code, no pre-scan needed."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Shearing` is that it a visual artifact occurring when a frame buffer incorrectly pushes a new frame while the monitor is still drawing the previous one.","answer":"False","explanation":"That describes Screen Tearing (a display sync issue). Shearing slants an object along one axis—like italicizing text."},
    {"type":"mcq","q":"Applying a uniform spatial Smoothing Filter (1/9) perfectly centered over a 3x3 pixel grid where all 9 underlying pixels possess exactly '246' luminance. What is the newly flattened center value calculated?<br><pre class='matrix-box'>\nImage Pixels:\n[ 246, 246, 246 ]\n[ 246, 246, 246 ]\n[ 246, 246, 246 ]\n</pre>","options":["27","0","255","246"],"answer":"246","explanation":"When all 9 pixels are identical, averaging them returns the same value. Smoothing only changes output when neighbors differ."},
    {"type":"fillInTheBlank","q":"Use Affine Translation Matrix calculus. Translate coordinate [x=14, y=8] by [Tx=2, Ty=-8]. What is the resulting <b>X</b> coordinate?<br><pre class='matrix-box'>\n[ 1, 0,   2 ]   [ 14 ]\n[ 0, 1,  -8 ] x [  8 ]\n[ 0, 0,   1 ]   [  1 ]\n</pre>","answer":"16","explanation":"New X = x + Tx = 14 + (2) = 16. Translation simply adds the offset to each coordinate."},
    {"type":"mcq","q":"Based implicitly on 24-bit Additive RGB display arrays, what bright vivid color generates when a single screen pixel is triggered using this literal 3-dimensional data grid?<br><pre class='matrix-box'>\nRed Buffer:   [0]\nGreen Buffer: [255]\nBlue Buffer:  [255]\n</pre>","options":["Magenta","Cyan","Black","White"],"answer":"Cyan","explanation":"Green(255) + Blue(255) with no Red = Cyan in additive light. Cyan is red's complement."},
    {"type":"matchFollowing","q":"Match the following critical Media Technology principles directly with their exact technical definitions from the PDFs:","pairs":[{"left":"Huffman Coding","right":"A compression system allocating incredibly short binary codes to frequent characters and long codes to rare characters."},{"left":"Lossy Compression","right":"Algorithms like JPEG that permanently destroy high-frequency visual data to attain massively smaller file sizes."},{"left":"Smoothing Filter","right":"A spatial kernel assigning identical fractional weights to physically blur high-frequency noise."},{"left":"Indentation","right":"Mandatory structural spacing in Python strictly dictating exactly which code belongs inside a specific logical control block."}],"explanation":"Each term has a precise technical meaning—focus on what makes each one unique in function, domain, and application."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"A dynamic Python sequence defined by brackets `[]` that permits continuous internal insertion and deletion.\"","options":["Frame Buffer","Cones","Grayscale","List"],"answer":"List","explanation":"Python lists use [] brackets and are mutable: you can freely append, insert, or remove elements after creation."},
    {"type":"fillInTheBlank","q":"The dominant wavelength of light defining the fundamental color family. This explicit scientific mechanism is universally referred to as _________.","answer":"Hue","explanation":"Hue is the position on the color wheel (red, green, blue, etc.)—it defines the color family independent of brightness or vividness."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Additive Primary Colors` is that it red, green, and blue light, which combine vividly to form pure white.","answer":"True","explanation":"Correct—monitors emit R/G/B light, and combining all three at full intensity produces white. The opposite of paint mixing."},
    {"type":"fillInTheBlank","q":"Use Affine Translation Matrix calculus. Translate coordinate [x=9, y=3] by [Tx=4, Ty=0]. What is the resulting <b>X</b> coordinate?<br><pre class='matrix-box'>\n[ 1, 0,   4 ]   [  9 ]\n[ 0, 1,   0 ] x [  3 ]\n[ 0, 0,   1 ]   [  1 ]\n</pre>","answer":"13","explanation":"New X = x + Tx = 9 + (4) = 13. Translation simply adds the offset to each coordinate."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"A visual artifact occurring when a frame buffer incorrectly pushes a new frame while the monitor is still drawing the previous one.\"","options":["Generation Loss","Screen Tearing","Cones","Histogram Equalization"],"answer":"Screen Tearing","explanation":"Screen tearing happens when the GPU pushes a new frame while the display is mid-draw, creating a visible horizontal split."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"The mathematical law dictating that Rotating then Translating yields a distinctly different result than Translating then Rotating.\"","options":["Translation","Histogram","Non-Commutative Matrices","Image Slicing"],"answer":"Non-Commutative Matrices","explanation":"Matrix multiplication is order-dependent: Rotate→Translate gives a different result than Translate→Rotate because each operation changes the coordinate system."},
    {"type":"fillInTheBlank","q":"You securely compress an unformatted 112 MB BMP media file algorithmically down to a final layout size of 14 MB using the Lossless Huffman methodology. What is the isolated compression ratio integer? (e.g. if 9:1, write 9).","answer":"8","explanation":"Compression Ratio = Original ÷ Compressed = 112 ÷ 14 = 8. This means the file became 8× smaller."},
    {"type":"fillInTheBlank","q":"You securely compress an unformatted 10 MB BMP media file algorithmically down to a final layout size of 2 MB using the Lossless Huffman methodology. What is the isolated compression ratio integer? (e.g. if 9:1, write 9).","answer":"5","explanation":"Compression Ratio = Original ÷ Compressed = 10 ÷ 2 = 5. This means the file became 5× smaller."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `LZW Algorithm` is that it copying the exact literal border pixels of an image outwards to prevent filter anomalies at the edges.","answer":"False","explanation":"LZW is a dictionary-based compression algorithm. The description given matches a completely different concept."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Luminance` is that it the geometric mathematical division of the original uncompressed file size by the new compressed file size.","answer":"False","explanation":"Luminance = pixel brightness. Compression Ratio = original÷compressed size. They measure entirely different things."},
    {"type":"fillInTheBlank","q":"An elemental Python library allowing drastically faster C-backed operations over massive 2D pixel image arrays. This explicit scientific mechanism is universally referred to as _________.","answer":"Numpy","explanation":"NumPy gives Python fast C-backed array math, letting you manipulate entire pixel grids as 2D matrices in one operation."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"An elemental Python library allowing drastically faster C-backed operations over massive 2D pixel image arrays.\"","options":["Generation Loss","Translation","Zero Padding","Numpy"],"answer":"Numpy","explanation":"NumPy gives Python fast C-backed array math, letting you manipulate entire pixel grids as 2D matrices in one operation."},
    {"type":"mcq","q":"Based implicitly on 24-bit Additive RGB display arrays, what bright vivid color generates when a single screen pixel is triggered using this literal 3-dimensional data grid?<br><pre class='matrix-box'>\nRed Buffer:   [255]\nGreen Buffer: [0]\nBlue Buffer:  [255]\n</pre>","options":["Magenta","Yellow","White","Red"],"answer":"Magenta","explanation":"Red(255) + Blue(255) with no Green = Magenta. It's the red-blue mix in additive color."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `LZW Algorithm` is that it an 8-bit color depth system allowing precisely 256 unique shades from black to white.","answer":"False","explanation":"LZW is a dictionary-based compression algorithm. The description given matches a completely different concept."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Screen Tearing` is that it a dynamic python sequence defined by brackets `[]` that permits continuous internal insertion and deletion.","answer":"False","explanation":"Screen Tearing is a display rendering artifact. A Python List is a data container using []. Completely unrelated."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"Copying the exact literal border pixels of an image outwards to prevent filter anomalies at the edges.\"","options":["Edge Replication","Generation Loss","Smoothing Filter","Zero Padding"],"answer":"Edge Replication","explanation":"Edge replication copies the outermost border pixels outward, giving convolution kernels valid neighbors at image boundaries."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Edge Replication` is that it copying the exact literal border pixels of an image outwards to prevent filter anomalies at the edges.","answer":"True","explanation":"Yes—edge replication extends border pixels outward so convolution kernels have valid data at image boundaries."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Luminance` is that it the objective mathematical brightness or intensity of a pixel.","answer":"True","explanation":"Correct—luminance measures perceived brightness independent of color. A bright red and bright green can have similar luminance."},
    {"type":"fillInTheBlank","q":"Use Affine Translation Matrix calculus. Translate coordinate [x=6, y=11] by [Tx=-2, Ty=-5]. What is the resulting <b>X</b> coordinate?<br><pre class='matrix-box'>\n[ 1, 0,  -2 ]   [  6 ]\n[ 0, 1,  -5 ] x [ 11 ]\n[ 0, 0,   1 ]   [  1 ]\n</pre>","answer":"4","explanation":"New X = x + Tx = 6 + (-2) = 4. Translation simply adds the offset to each coordinate."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Saturation` is that it a spatial kernel assigning identical fractional weights to physically blur high-frequency noise.","answer":"False","explanation":"Saturation = color purity/vividness. A smoothing filter is a spatial blur operation. Different domains entirely."},
    {"type":"mcq","q":"Based implicitly on 24-bit Additive RGB display arrays, what bright vivid color generates when a single screen pixel is triggered using this literal 3-dimensional data grid?<br><pre class='matrix-box'>\nRed Buffer:   [255]\nGreen Buffer: [255]\nBlue Buffer:  [0]\n</pre>","options":["Red","Yellow","Magenta","White"],"answer":"Yellow","explanation":"Red(255) + Green(255) with no Blue = Yellow. Red and green light combine to produce yellow."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"The vividness or purity of a color decoupled from its brightness.\"","options":["Luminance","Zero Padding","Saturation","Lossless Compression"],"answer":"Saturation","explanation":"Saturation measures color purity/vividness. High saturation = vivid color; low saturation = washed-out gray tone."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"A mathematical matrix holding a strong positive center and negative edges to isolate and amplify stark structural lines.\"","options":["Histogram Equalization","Sharpening Kernel","Lossless Compression","Scaling"],"answer":"Sharpening Kernel","explanation":"A sharpening kernel has a large positive center surrounded by negative weights, amplifying the difference between each pixel and its neighbors."},
    {"type":"fillInTheBlank","q":"The geometric mathematical division of the original uncompressed file size by the new compressed file size. This explicit scientific mechanism is universally referred to as _________.","answer":"Compression Ratio","explanation":"Compression Ratio = Original Size ÷ Compressed Size. It tells you how many times smaller the compressed file became."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"A strict linear mapping technique that absolutely preserves perfectly parallel lines.\"","options":["Raster Scan","Affine Transformation","Lossy Compression","Sharpening Kernel"],"answer":"Affine Transformation","explanation":"Affine transformations (translate, rotate, scale, shear) always preserve parallel lines—they cannot bend straight lines into curves."},
    {"type":"fillInTheBlank","q":"Algorithms that guarantee 100% perfect bit-for-bit reconstruction of the original file data upon decompression. This explicit scientific mechanism is universally referred to as _________.","answer":"Lossless Compression","explanation":"Lossless compression (PNG, ZIP, FLAC) guarantees perfect reconstruction—every single bit is recovered on decompression."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Spatial Filtering` is that it an operation modifying a pixel's strict brightness based immediately on its localized neighbours.","answer":"True","explanation":"Yes—spatial filters use a kernel to compute each pixel's new value from its local neighborhood."},
    {"type":"fillInTheBlank","q":"Cyan, Magenta, and Yellow ink, which combine heavily to form Black. This explicit scientific mechanism is universally referred to as _________.","answer":"Subtractive Primary Colors","explanation":"CMY inks absorb (subtract) light wavelengths from white paper. Mixing all three absorbs everything, producing black."},
    {"type":"fillInTheBlank","q":"A dynamic dictionary-based compressor that naturally discovers and records repeating string fragments on the fly. This explicit scientific mechanism is universally referred to as _________.","answer":"LZW Algorithm","explanation":"LZW dynamically builds a dictionary as it scans input—each new repeated pattern gets a shorter code, no pre-scan needed."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Smoothing Filter` is that it a spatial kernel assigning identical fractional weights to physically blur high-frequency noise.","answer":"True","explanation":"Correct—a smoothing/averaging filter gives equal weight to all neighbors (1/9 each for 3×3), blurring sharp edges."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Scaling` is that it multiplies x and y coordinates to physically enlarge or shrink an entire image structure.","answer":"True","explanation":"Yes—scaling multiplies coordinates by Sx/Sy factors. Values >1 enlarge, <1 shrink the image."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Numpy` is that it biological receptors in the human retina explicitly responsible for perceiving sharp color.","answer":"False","explanation":"NumPy is a Python math library for fast array ops. Cones are biological eye cells—software vs. biology."},
    {"type":"fillInTheBlank","q":"The smallest fundamentally controllable element of a picture represented on a screen. This explicit scientific mechanism is universally referred to as _________.","answer":"Pixel","explanation":"A pixel (picture element) is the smallest individually controllable dot on a display—every digital image is a grid of pixels."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Zero Padding` is that it temporarily wrapping an image border in pure 0 values to prevent mathematical crashing when a kernel slides off-screen.","answer":"True","explanation":"Correct—zero padding wraps the image in 0-value pixels so edge kernels don't read outside the image bounds."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Tuple` is that it a python sequence array defined strictly by parentheses `()` that mathematically cannot be modified or altered after creation.","answer":"True","explanation":"Yes—Python tuples are defined with () and are immutable. Once created, you cannot add, remove, or change elements."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Histogram Equalization` is that it multiplies x and y coordinates to physically enlarge or shrink an entire image structure.","answer":"False","explanation":"Histogram equalization redistributes brightness for better contrast. Scaling changes size via coordinate multiplication."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Non-Commutative Matrices` is that it the perpetual degrading physical damage caused by repeatedly unzipping and explicitly re-saving lossy files like jpeg.","answer":"False","explanation":"Non-commutativity means A×B ≠ B×A in matrix math. Generation loss is quality degradation from repeated lossy re-saves."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Resolution` is that it the exact geometric pixel width multiplied by the physical pixel height of a screen.","answer":"True","explanation":"Correct—resolution is width × height in pixels (e.g., 1920×1080). More pixels = finer detail."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"Algorithms that guarantee 100% perfect bit-for-bit reconstruction of the original file data upon decompression.\"","options":["Compression Ratio","Lossless Compression","Tuple","Frame Buffer"],"answer":"Lossless Compression","explanation":"Lossless compression (PNG, ZIP, FLAC) guarantees perfect reconstruction—every single bit is recovered on decompression."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"An algorithm perfectly compressing data sequences consisting of extremely long identical consecutive values.\"","options":["Subtractive Primary Colors","Lossless Compression","Run-Length Encoding","Frame Buffer"],"answer":"Run-Length Encoding","explanation":"RLE replaces consecutive identical values with a count+value pair (e.g., 'AAAA' → '4A'), ideal for data with long uniform runs."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"The Python Numpy logic using `array[start:end]` to geometrically crop strict segments out of full resolution grids.\"","options":["Image Slicing","Hue","Scaling","Lossy Compression"],"answer":"Image Slicing","explanation":"NumPy slicing array[start:end] lets you crop rectangular regions from images without writing loops—fast and memory-efficient."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"Biological receptors in the human retina explicitly responsible for perceiving sharp color.\"","options":["Luminance","Resolution","Cones","Scaling"],"answer":"Cones","explanation":"Cone cells in the retina come in three types (R/G/B) and enable color vision in bright light, concentrated in the fovea."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"Paints the screen sequentially, row-by-row from top to bottom.\"","options":["List","Edge Replication","Raster Scan","Monochrome"],"answer":"Raster Scan","explanation":"Raster scanning draws the screen line-by-line from top-left to bottom-right, the standard refresh method for CRT and LCD displays."},
    {"type":"fillInTheBlank","q":"Copying the exact literal border pixels of an image outwards to prevent filter anomalies at the edges. This explicit scientific mechanism is universally referred to as _________.","answer":"Edge Replication","explanation":"Edge replication copies the outermost border pixels outward, giving convolution kernels valid neighbors at image boundaries."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `List` is that it mathematically shifts an image's x and y coordinates without modifying its size or angle.","answer":"False","explanation":"A Python List stores mutable data in []. Translation shifts image coordinates. Different domains entirely."},
    {"type":"fillInTheBlank","q":"The vividness or purity of a color decoupled from its brightness. This explicit scientific mechanism is universally referred to as _________.","answer":"Saturation","explanation":"Saturation measures color purity/vividness. High saturation = vivid color; low saturation = washed-out gray tone."},
    {"type":"fillInTheBlank","q":"Biological receptors in the human retina highly sensitive to dim light but incapable of determining color. This explicit scientific mechanism is universally referred to as _________.","answer":"Rods","explanation":"Rod cells handle dim-light vision and peripheral sight. They vastly outnumber cones but can only detect brightness, not color."},
    {"type":"fillInTheBlank","q":"A 1-bit color depth display where pixels can strictly only be pure black or pure white. This explicit scientific mechanism is universally referred to as _________.","answer":"Monochrome","explanation":"Monochrome uses 1 bit per pixel—just black or white, no shades. The simplest possible image representation."},
    {"type":"mcq","q":"Which term perfectly matches this fundamental definition from the PDF lectures:\n\"Mandatory structural spacing in Python strictly dictating exactly which code belongs inside a specific logical control block.\"","options":["Rods","Indentation","Sharpening Kernel","Screen Tearing"],"answer":"Indentation","explanation":"Python uses whitespace indentation to define code blocks instead of braces {}. Wrong indentation = syntax error."},
    {"type":"trueFalse","q":"True or False: The defining architectural characteristic of `Image Slicing` is that it the python numpy logic using `array[start:end]` to geometrically crop strict segments out of full resolution grids.","answer":"True","explanation":"Yes—NumPy's array[start:end] slice notation extracts sub-regions directly from the pixel matrix without loops."},
    {"type":"fillInTheBlank","q":"Mandatory structural spacing in Python strictly dictating exactly which code belongs inside a specific logical control block. This explicit scientific mechanism is universally referred to as _________.","answer":"Indentation","explanation":"Python uses whitespace indentation to define code blocks instead of braces {}. Wrong indentation = syntax error."},
    {"type":"fillInTheBlank","q":"Stores the exact pixel intensity states of a completed frame before sending it to the display. This explicit scientific mechanism is universally referred to as _________.","answer":"Frame Buffer","explanation":"The frame buffer is dedicated GPU memory storing complete pixel data for the current frame before the display reads it."},
    {"type":"fillInTheBlank","q":"A Python sequence array defined strictly by parentheses `()` that mathematically cannot be modified or altered after creation. This explicit scientific mechanism is universally referred to as _________.","answer":"Tuple","explanation":"Python tuples use () and are immutable—once created, elements can't be changed. Useful for fixed data like coordinates or RGB values."},

    // ═══════════════════════════════════════════════════════════════
    // TCA EXAM SECTION TYPE QUESTIONS (Applied / Exam-Style)
    // ═══════════════════════════════════════════════════════════════

    // ── LZW Compression Step-by-Step ──────────────────────────────
    {"type":"fillInTheBlank","q":"Given the string <b>ABABABAB</b>, walk through LZW compression step by step. The initial dictionary has A=65, B=66. Produce the final output code sequence (comma-separated).<br><pre class='matrix-box'>\nStep 1: Read A → output 65, add AB=256\nStep 2: Read B → output 66, add BA=257\nStep 3: Read AB → output 256, add ABA=258\nStep 4: Read ABA → output 258\nStep 5: Read B → output 66\n</pre>","answer":"65,66,256,258,66","explanation":"LZW builds its dictionary dynamically. Each time a new pattern is found, the previous match is output and the new longer pattern is added to the dictionary. Output: 65(A), 66(B), 256(AB), 258(ABA), 66(B)."},

    {"type":"fillInTheBlank","q":"Given the string <b>AABABC</b>, walk through LZW compression. The initial dictionary has A=65, B=66, C=67. What is the output code sequence (comma-separated)?<br><pre class='matrix-box'>\nStep 1: Read A → output 65, add AA=256\nStep 2: Read A → matches A, read AB → output 65, add AB=257\nStep 3: Read B → output 66, add BA=258\nWait... let's retrace carefully:\nStep 1: A → output 65, add AA=256\nStep 2: AA → output 256, add AAB=259\nStep 3: B → output 66, add BA=258... \n</pre>\nHint: Output the final comma-separated codes.","answer":"65,256,66,65,67","explanation":"Walking through LZW: Read A(65), AA matches dict entry 256→output 256, B(66) is next, then A(65), then C(67). The dictionary grows with each new pair encountered."},

    {"type":"mcq","q":"During LZW compression of the string 'ABABABA', what happens when the algorithm encounters the substring 'AB' for the second time?","options":["It outputs the ASCII code for A and B separately","It outputs the dictionary code 256 (the previously stored AB entry)","It creates a new dictionary entry and outputs nothing","It restarts the dictionary from scratch"],"answer":"It outputs the dictionary code 256 (the previously stored AB entry)","explanation":"LZW's power comes from reusing dictionary entries. The first time 'AB' is seen, it's added as entry 256. The second time, 'AB' is recognized as a single unit and output as code 256 instead of two separate codes."},

    {"type":"trueFalse","q":"In LZW compression, the dictionary must be transmitted alongside the compressed data for the decoder to reconstruct the original string.","answer":"False","explanation":"LZW is special because the decoder can rebuild the exact same dictionary from the compressed codes alone. No separate dictionary transmission is needed—the decoder mirrors the encoder's dictionary-building process."},

    {"type":"mcq","q":"What is the maximum number of dictionary entries LZW can create when using 12-bit codes?","options":["256","1024","4096","65536"],"answer":"4096","explanation":"With 12-bit codes, LZW can address 2^12 = 4096 entries. The first 256 (0-255) are reserved for single ASCII characters, leaving 3840 slots for new patterns discovered during compression."},

    // ── Huffman Coding Calculations ───────────────────────────────
    {"type":"fillInTheBlank","q":"A string of <b>\"advantage\"</b> is encoded using Huffman coding. The total number of bits required after encoding is 24 bits, while the original string was stored using 8-bit ASCII per character. Calculate the compression ratio and express it as a percentage.","answer":"300","explanation":"Original: 9 characters × 8 bits = 72 bits. Compressed: 24 bits. Compression Ratio = 72 ÷ 24 = 3.0 → expressed as percentage = 300%."},

    {"type":"fillInTheBlank","q":"If a Huffman code uses 3 bits on average per symbol for a dataset of 2000 symbols, what is the total compressed size in bits?","answer":"6000","explanation":"Total bits = number of symbols × average bits per symbol = 2000 × 3 = 6000 bits."},

    {"type":"mcq","q":"What is the first step in the Huffman encoding process?","options":["Assigning random binary codes","Assigning fixed-length codes to characters","Splitting characters into equal parts","Sorting characters by frequency"],"answer":"Sorting characters by frequency","explanation":"Huffman encoding starts by counting the frequency of each character, then sorting them. The two least frequent characters are combined first, building a binary tree from the bottom up."},

    {"type":"mcq","q":"What is the main advantage of Huffman coding over fixed-length encoding?","options":["It is only used for image compression","It ensures a fixed-length encoding","It always produces a 1:1 character-to-binary conversion","It assigns shorter codes to more frequent characters"],"answer":"It assigns shorter codes to more frequent characters","explanation":"Huffman's variable-length coding assigns the shortest binary codes to the most frequent characters, ensuring the total encoded message is shorter than fixed-length alternatives like ASCII."},

    {"type":"fillInTheBlank","q":"In Huffman coding, the string <b>'AABBCCDD'</b> has equal frequency for all characters (each appears twice). If each character gets a 2-bit code, what is the total compressed size in bits?","answer":"16","explanation":"8 characters × 2 bits each = 16 bits. When all characters have equal frequency, Huffman produces codes of equal length, similar to fixed-length encoding."},

    {"type":"trueFalse","q":"In Huffman coding, two different characters can have the same binary code.","answer":"False","explanation":"Huffman coding produces a prefix-free code—no code is a prefix of another. This guarantees every character has a unique binary representation, enabling unambiguous decoding."},

    {"type":"mcq","q":"In Huffman coding, what determines the length of a character's binary code?","options":["The total number of unique characters","The ASCII value of the character","The frequency of occurrence in the text","The position of the character in the input string"],"answer":"The frequency of occurrence in the text","explanation":"Characters appearing most frequently get the shortest codes. The Huffman tree places high-frequency characters near the root (short path = short code) and rare characters deeper (long path = long code)."},

    // ── Convolution Filtering (Applied) ───────────────────────────
    {"type":"fillInTheBlank","q":"John applies the given 3×3 filter to the grayscale image. Calculate the new value for the central pixel after convolution.<br><pre class='matrix-box'>\nImage Pixels:     Filter Weights:\n[ 1,  2,  1 ]     [ 0,  1,  0 ]\n[ 2,  0,  2 ]  ×  [ 1,  1,  1 ]\n[ 1,  2,  1 ]     [ 0,  1,  0 ]\n</pre>\nHint: Multiply each pixel by the corresponding weight and sum all 9 results.","answer":"8","explanation":"Convolution: (1×0)+(2×1)+(1×0) + (2×1)+(0×1)+(2×1) + (1×0)+(2×1)+(1×0) = 0+2+0+2+0+2+0+2+0 = 8. The filter selectively picks the cross-shaped neighbors."},

    {"type":"fillInTheBlank","q":"John applies a 3×3 averaging filter (all weights = 1/9) to the given grayscale image. Calculate the new intensity value of the central pixel.<br><pre class='matrix-box'>\nImage Pixels:\n[ 3,  4,  3 ]\n[ 4,  8,  4 ]\n[ 3,  4,  3 ]\n</pre>","answer":"4","explanation":"Sum all 9 pixels: 3+4+3+4+8+4+3+4+3 = 36. Divide by 9 (averaging): 36÷9 = 4. The averaging filter smooths the bright center pixel toward its darker neighbors."},

    {"type":"fillInTheBlank","q":"Apply the following sharpening kernel to the image region. What is the output value for the central pixel?<br><pre class='matrix-box'>\nImage Pixels:     Sharpening Kernel:\n[ 10, 10, 10 ]     [  0, -1,  0 ]\n[ 10, 20, 10 ]  ×  [ -1,  5, -1 ]\n[ 10, 10, 10 ]     [  0, -1,  0 ]\n</pre>","answer":"60","explanation":"(10×0)+(10×-1)+(10×0) + (10×-1)+(20×5)+(10×-1) + (10×0)+(10×-1)+(10×0) = 0-10+0-10+100-10+0-10+0 = 60. The sharpening kernel amplifies the center pixel's difference from its neighbors."},

    {"type":"fillInTheBlank","q":"Apply the following weighted smoothing kernel to compute the new central pixel value.<br><pre class='matrix-box'>\nImage Pixels:       Weighted Filter:\n[ 1, 10,  5 ]     [ 1/16,  2/16,  1/16 ]\n[ 2, 12,  6 ]  ×  [ 2/16,  4/16,  2/16 ]\n[ 2,  4, 10 ]     [ 1/16,  2/16,  1/16 ]\n</pre>\nRound to the nearest integer.","answer":"7","explanation":"Sum = (1×1 + 10×2 + 5×1 + 2×2 + 12×4 + 6×2 + 2×1 + 4×2 + 10×1) ÷ 16 = (1+20+5+4+48+12+2+8+10)÷16 = 110÷16 = 6.875 ≈ 7. The center pixel gets the most weight (4/16), giving it the strongest influence."},

    {"type":"mcq","q":"When a 3×3 convolution kernel is placed on a corner pixel of an image, what problem occurs?","options":["The pixel value becomes negative","The kernel extends beyond the image boundary where no data exists","The image resolution doubles","The pixel automatically becomes zero"],"answer":"The kernel extends beyond the image boundary where no data exists","explanation":"At boundaries, the kernel needs pixel data that doesn't exist outside the image. Solutions include zero-padding (filling with 0s), edge replication (copying border values outward), or simply cropping the output."},

    {"type":"mcq","q":"Which solution to the boundary problem introduces the least amount of artificial data into the filtered image?","options":["Zero padding","Edge replication","Mirror padding","Cropping the output"],"answer":"Edge replication","explanation":"Edge replication duplicates existing border pixel values, which is more natural than zero padding (introduces dark artifacts) or mirror padding. Cropping avoids the issue entirely but reduces image size."},

    // ── Histogram Analysis ────────────────────────────────────────
    {"type":"mcq","q":"What is the primary reason for analyzing an image histogram?","options":["To enhance the color intensity of an image","To measure an image's brightness distribution","To determine the exact pixel size of an image","To count the number of objects in an image"],"answer":"To measure an image's brightness distribution","explanation":"A histogram plots pixel count (y-axis) vs brightness level (x-axis, 0-255). It reveals whether an image is underexposed (clustered left), overexposed (clustered right), or well-balanced (spread evenly)."},

    {"type":"mcq","q":"What change in an image histogram suggests a loss of information?","options":["Histogram becomes smoother","Histogram has missing bars or gaps","Histogram shifts entirely to the right","Histogram remains unchanged"],"answer":"Histogram has missing bars or gaps","explanation":"Gaps in a histogram mean certain brightness levels have zero pixels—information was lost. This typically happens after aggressive contrast stretching or quantization, where continuous tonal ranges get collapsed."},

    {"type":"trueFalse","q":"A perfectly uniform histogram means every brightness level (0-255) has the exact same number of pixels.","answer":"True","explanation":"Histogram equalization aims for this ideal: spreading pixels evenly across all brightness levels to maximize contrast. In practice, perfect uniformity is rare but the algorithm gets close."},

    {"type":"mcq","q":"An image histogram is heavily clustered on the left side (values 0-50). What does this indicate about the image?","options":["The image is overexposed (too bright)","The image is underexposed (too dark)","The image has perfect contrast","The image is a binary black/white image"],"answer":"The image is underexposed (too dark)","explanation":"Left-clustered histograms show most pixels have low brightness values (close to 0 = black). The image lacks bright tones and appears dark overall. Histogram equalization can redistribute these values."},

    {"type":"trueFalse","q":"Histogram equalization always improves image quality.","answer":"False","explanation":"Histogram equalization can over-amplify noise in low-contrast regions and may wash out already well-distributed images. It works best on images with poor contrast distribution."},

    // ── Laplacian / Edge Detection ─────────────────────────────────
    {"type":"mcq","q":"Which of the following statements best describes Laplacian image enhancement?","options":["It sharpens an image by emphasizing edges and fine details","It performs histogram equalization to enhance contrast","It blurs high-frequency components of an image","It reduces noise through Gaussian smoothing"],"answer":"It sharpens an image by emphasizing edges and fine details","explanation":"The Laplacian operator computes second-order derivatives, detecting rapid intensity changes (edges). Adding the Laplacian result back to the original image enhances edge sharpness."},

    {"type":"mcq","q":"In image sharpening using the Laplacian operator, the final enhanced image is obtained by:","options":["Adding the Laplacian filtered image to the original image","Subtracting the Laplacian filtered image from the original image","Dividing the original image by the Laplacian result","Multiplying the Laplacian by a Gaussian kernel"],"answer":"Subtracting the Laplacian filtered image from the original image","explanation":"The negative Laplacian produces negative values at edges. Subtracting it from the original effectively adds edge emphasis: Enhanced = Original - (negative Laplacian) = Original + |edges|."},

    {"type":"trueFalse","q":"Edge detection is an example of a spatial filtering technique used in image processing.","answer":"True","explanation":"Edge detection kernels (Sobel, Prewitt, Canny, Laplacian) all operate directly on pixel neighborhoods in the spatial domain, making them spatial filters by definition."},

    {"type":"mcq","q":"What type of image processing technique is best suited for detecting cracks in eggs using back-light images?","options":["Histogram equalization","Color thresholding","Fourier Transform","Edge detection (Sobel or Canny)"],"answer":"Edge detection (Sobel or Canny)","explanation":"Cracks appear as sharp, thin lines of intensity change against a smooth shell. Edge detectors like Sobel or Canny are specifically designed to find such rapid intensity transitions."},

    {"type":"trueFalse","q":"Convolution-based spatial filtering always reduces image noise.","answer":"False","explanation":"Only smoothing filters reduce noise. Sharpening filters (Laplacian, high-pass) actually amplify noise alongside edges, since noise consists of high-frequency intensity variations that sharpening enhances."},

    {"type":"mcq","q":"What is the purpose of spatial filtering in image processing?","options":["To detect and enhance features like edges or smooth images","To change the image resolution","To modify pixel intensities independently","To convert an image into a binary format"],"answer":"To detect and enhance features like edges or smooth images","explanation":"Spatial filtering uses kernels that operate on local pixel neighborhoods to achieve effects like blurring (smoothing kernels), sharpening (Laplacian), or edge detection (Sobel/Canny)."},

    // ── Homogeneous Transformation Matrices ────────────────────────
    {"type":"mcq","q":"What transformations are applied in the given homogeneous transformation matrix?<br><pre class='matrix-box'>\n[ Sx·cos(θ), -Sy·sin(θ), Tx ]\n[ Sx·sin(θ),  Sy·cos(θ), Ty ]\n[         0,          0,  1 ]\n</pre>","options":["Rotation, Scaling, and Translation","Rotation, Translation, and Shearing","Scaling, Rotation, and Reflection","Translation, Rotation, and Scaling"],"answer":"Rotation, Scaling, and Translation","explanation":"The matrix combines three operations: Sx/Sy factors provide Scaling, sin(θ)/cos(θ) terms provide Rotation, and Tx/Ty in the third column provide Translation. All in one matrix multiplication."},

    {"type":"trueFalse","q":"In homogeneous transformation, applying translation before rotation results in a different final position than applying rotation before translation.","answer":"True","explanation":"Matrix multiplication is non-commutative: T×R ≠ R×T. Translating then rotating moves the object and rotates around the new position. Rotating then translating rotates in place, then shifts."},

    {"type":"fillInTheBlank","q":"Apply the following 2D scaling matrix to point (3, 5). What is the new <b>X</b> coordinate?<br><pre class='matrix-box'>\n[ 2, 0, 0 ]   [ 3 ]\n[ 0, 3, 0 ] × [ 5 ]\n[ 0, 0, 1 ]   [ 1 ]\n</pre>","answer":"6","explanation":"New X = Sx × x = 2 × 3 = 6. The scaling matrix multiplies each coordinate by its respective scale factor independently."},

    {"type":"fillInTheBlank","q":"Apply the following 2D scaling matrix to point (3, 5). What is the new <b>Y</b> coordinate?<br><pre class='matrix-box'>\n[ 2, 0, 0 ]   [ 3 ]\n[ 0, 3, 0 ] × [ 5 ]\n[ 0, 0, 1 ]   [ 1 ]\n</pre>","answer":"15","explanation":"New Y = Sy × y = 3 × 5 = 15. The Y scale factor (3) stretches the Y coordinate to triple its original value."},

    {"type":"mcq","q":"Which matrix is the Identity Matrix for 2D transformations?<br><pre class='matrix-box'>\nA)              B)              C)\n[ 1, 0, 0 ]    [ 0, 0, 0 ]    [ 2, 0, 0 ]\n[ 0, 1, 0 ]    [ 0, 0, 0 ]    [ 0, 2, 0 ]\n[ 0, 0, 1 ]    [ 0, 0, 0 ]    [ 0, 0, 1 ]\n</pre>","options":["Matrix A","Matrix B","Matrix C","None of the above"],"answer":"Matrix A","explanation":"The identity matrix has 1s on the diagonal and 0s everywhere else. Multiplying any point by it returns the same point—zero transformation. Matrix B would collapse everything to the origin; Matrix C doubles the size."},

    {"type":"fillInTheBlank","q":"Translate the point (8, 12) using the matrix below. What is the new <b>Y</b> coordinate?<br><pre class='matrix-box'>\n[ 1, 0,  5 ]   [  8 ]\n[ 0, 1, -3 ] × [ 12 ]\n[ 0, 0,  1 ]   [  1 ]\n</pre>","answer":"9","explanation":"New Y = y + Ty = 12 + (-3) = 9. Translation adds the offset to each coordinate without changing size or angle."},

    {"type":"trueFalse","q":"A shearing transformation preserves the area of a shape while changing its angles.","answer":"True","explanation":"Shearing slants an object along one axis (like italicizing text). While angles change, the total area remains constant—no pixels are added or removed, just repositioned."},

    // ── RGB Subpixel & Color Theory (Applied) ─────────────────────
    {"type":"mcq","q":"Why does an LCD display use an RGBG subpixel arrangement instead of standard RGB?","options":["To reduce power consumption","To make colors appear more natural","To improve sharpness and human eye perception of green","To allow for better contrast in grayscale images"],"answer":"To improve sharpness and human eye perception of green","explanation":"The human eye has peak sensitivity to green wavelengths. RGBG (PenTile) layouts dedicate extra subpixels to green, boosting perceived sharpness without increasing total subpixel count."},

    {"type":"fillInTheBlank","q":"The human eye is more sensitive to the color ____, which is why modern LCD screens use the RGBG subpixel arrangement.","answer":"green","explanation":"Human cone cells have peak sensitivity around 555nm (green). This biological fact drives display engineering decisions like PenTile RGBG layouts and luminance weighting formulas."},

    {"type":"trueFalse","q":"In an RGB subpixel arrangement, each pixel is made up of equally sized red, green, and blue subpixels.","answer":"True","explanation":"In a standard RGB stripe layout, each pixel contains three equally-sized subpixel columns: one red, one green, one blue. PenTile/RGBG is a different arrangement that breaks this equal-size pattern."},

    {"type":"fillInTheBlank","q":"To ____ an RGB color, we increase the difference between the most and least intense color channels while keeping the brightness unchanged.","answer":"saturate","explanation":"Saturation = color purity. Increasing the gap between the strongest and weakest RGB channels makes the color more vivid (saturated) without affecting overall luminance."},

    {"type":"trueFalse","q":"Fully saturating an RGB color increases its brightness.","answer":"False","explanation":"Saturation controls purity/vividness only. Brightness (luminance) is a separate property. You can have a fully saturated dark red or a desaturated bright gray—they're independent dimensions."},

    {"type":"trueFalse","q":"Increasing image contrast always improves image quality without any drawbacks.","answer":"False","explanation":"Excessive contrast causes clipping—bright areas blow out to pure white and dark areas crush to pure black. Detail in highlights and shadows is permanently destroyed."},

    {"type":"mcq","q":"What happens when an image is over-processed during enhancement?","options":["Irreversible distortion occurs due to lost details","Image gains more colors than it originally had","Image details improve significantly","Histogram becomes more uniform"],"answer":"Irreversible distortion occurs due to lost details","explanation":"Over-processing clips pixel values at extremes (0 and 255), posterizes smooth gradients into flat blocks, and amplifies noise. Once detail is clipped, it cannot be recovered."},

    // ── Spatial Filtering Applications ─────────────────────────────
    {"type":"mcq","q":"LZW compression works best when:","options":["The input is purely random","The input contains no repeated patterns","The input contains frequently repeated sequences","The input is extremely short"],"answer":"The input contains frequently repeated sequences","explanation":"LZW builds a dictionary of repeating patterns. More repetition = more dictionary hits = better compression. Random data has no patterns, so LZW adds overhead without benefit."},

    {"type":"mcq","q":"What is the primary reason LZW compression is used?","options":["It requires prior knowledge of character frequencies","It always provides better compression than Huffman coding","It builds a dictionary dynamically for repeated patterns","It replaces characters with fixed-length codes"],"answer":"It builds a dictionary dynamically for repeated patterns","explanation":"Unlike Huffman (which needs a pre-built frequency table), LZW discovers patterns on-the-fly. This makes it ideal for real-time compression of streams where the data characteristics aren't known in advance."},

    // ── Compression Ratio Word Problems ────────────────────────────
    {"type":"fillInTheBlank","q":"Using the LZW method, the word <b>\"advantage\"</b> is encoded, and the resulting compressed bit size is 32 bits. The original ASCII storage required 64 bits. Calculate the compression ratio.","answer":"2","explanation":"Compression Ratio = Original ÷ Compressed = 64 ÷ 32 = 2:1. The compressed file is exactly half the size of the original."},

    {"type":"trueFalse","q":"An image file of 200 KB is compressed to 50 KB using a lossless method. The compression ratio is 4:1.","answer":"True","explanation":"Compression Ratio = Original ÷ Compressed = 200 ÷ 50 = 4. The ratio is calculated by dividing original size by compressed size, giving 4:1."},

    {"type":"fillInTheBlank","q":"A 1920×1080 grayscale image uses 8 bits per pixel. What is its uncompressed file size in megabytes? (Use 1 MB = 1,000,000 bytes, round to 1 decimal)","answer":"2.1","explanation":"Total pixels = 1920 × 1080 = 2,073,600. At 8 bits (1 byte) per pixel = 2,073,600 bytes ≈ 2.1 MB."},

    {"type":"fillInTheBlank","q":"A 640×480 color image uses 24-bit RGB. What is the total uncompressed size in bytes?","answer":"921600","explanation":"Total pixels = 640 × 480 = 307,200. At 24 bits (3 bytes) per pixel: 307,200 × 3 = 921,600 bytes. This is why compression is essential for image storage!"},

    // ── Match-Following (TCA Exam Style) ──────────────────────────
    {"type":"matchFollowing","q":"Match the following image processing techniques with their effects:","pairs":[{"left":"Gaussian Blur","right":"Smooths noise by averaging neighboring pixels"},{"left":"Edge Detection (Canny)","right":"Highlights significant intensity changes"},{"left":"Histogram Equalization","right":"Redistributes brightness levels for uniform contrast"},{"left":"Convolution Filtering","right":"Uses a kernel matrix to apply spatial effects"}],"explanation":"Each technique serves a specific purpose: Gaussian blur reduces noise, Canny finds edges, histogram equalization fixes contrast, and convolution is the general mechanism underlying all spatial filters."},

    {"type":"matchFollowing","q":"Match the following terms with their correct descriptions:","pairs":[{"left":"Huffman Coding","right":"Uses variable-length binary codes based on character frequency"},{"left":"LZW Compression","right":"Creates a dictionary of repeating sequences dynamically"},{"left":"Lossless Encoding","right":"Ensures that no data is lost during compression"},{"left":"ASCII Encoding","right":"Uses fixed-length 8-bit binary representation for characters"}],"explanation":"Huffman and LZW are both lossless but work differently: Huffman uses frequency-based variable codes, LZW uses pattern dictionaries. ASCII is a fixed-length baseline that both aim to beat."},

    {"type":"matchFollowing","q":"Match the following image processing techniques with their effects:","pairs":[{"left":"Contrast Enhancement","right":"Expands brightness range, making details clearer"},{"left":"Histogram Equalization","right":"Redistributes brightness levels for uniform contrast"},{"left":"Clipping","right":"Cuts off pixel values at extremes, causing detail loss"},{"left":"Saturation Adjustment","right":"Alters color intensity without changing brightness"}],"explanation":"Contrast expansion and histogram equalization both improve visibility but risk clipping at extremes. Saturation operates on color purity independently of brightness."},

    {"type":"matchFollowing","q":"Match the boundary handling technique with its description:","pairs":[{"left":"Zero Padding","right":"Surrounds the image with 0-valued pixels before filtering"},{"left":"Edge Replication","right":"Copies border pixel values outward to fill missing data"},{"left":"Mirror Padding","right":"Reflects pixel values symmetrically at the boundary"},{"left":"Cropping","right":"Ignores edge pixels and produces a smaller output image"}],"explanation":"Each method handles the kernel-at-boundary problem differently. Zero padding adds dark artifacts, edge replication is most natural, mirror padding preserves gradients, and cropping avoids the issue at the cost of image size."},

    {"type":"matchFollowing","q":"Match each transformation with its matrix characteristic:","pairs":[{"left":"Translation","right":"Third column contains Tx and Ty offsets"},{"left":"Scaling","right":"Diagonal contains Sx and Sy multipliers"},{"left":"Rotation","right":"Contains sin(θ) and cos(θ) trigonometric terms"},{"left":"Identity","right":"Diagonal of 1s with all other elements 0"}],"explanation":"Each affine transformation has a distinctive matrix signature: translation uses the last column, scaling uses the diagonal, rotation uses trig functions, and the identity matrix applies zero change."},

    // ── Additional Applied Questions ──────────────────────────────
    {"type":"mcq","q":"A 3×3 averaging filter and a 5×5 averaging filter are both applied to the same noisy image. Which produces more blur?","options":["3×3 filter produces more blur","5×5 filter produces more blur","Both produce identical blur","Neither produces any blur"],"answer":"5×5 filter produces more blur","explanation":"Larger kernels average over more pixels, creating heavier smoothing. A 5×5 filter considers 25 neighbors vs 9 for 3×3, spreading each pixel's influence wider and producing more blur."},

    {"type":"fillInTheBlank","q":"A 24-bit color image has 3 channels (R, G, B), each with 8 bits. How many distinct colors can this image represent?","answer":"16777216","explanation":"Each channel has 2^8 = 256 levels. Total colors = 256 × 256 × 256 = 256³ = 16,777,216 (approximately 16.7 million colors). This is why 24-bit is called 'True Color'."},

    {"type":"mcq","q":"Which kernel would you use to detect vertical edges in an image?<br><pre class='matrix-box'>\nA) Sobel-X:        B) Sobel-Y:\n[-1, 0, 1]         [-1,-2,-1]\n[-2, 0, 2]         [ 0, 0, 0]\n[-1, 0, 1]         [ 1, 2, 1]\n</pre>","options":["Kernel A (Sobel-X)","Kernel B (Sobel-Y)","Both detect vertical edges","Neither detects edges"],"answer":"Kernel A (Sobel-X)","explanation":"Sobel-X detects vertical edges by computing horizontal intensity gradients (left-right differences). Sobel-Y detects horizontal edges by computing vertical gradients (top-bottom differences). The kernel orientation is perpendicular to the edge direction it detects."},

    {"type":"trueFalse","q":"A grayscale image with 8-bit depth can represent exactly 256 different shades from pure black to pure white.","answer":"True","explanation":"8 bits = 2^8 = 256 values (0 to 255). Value 0 represents pure black, 255 represents pure white, and values in between represent 254 shades of gray."},

    {"type":"fillInTheBlank","q":"If a monitor has a resolution of 1920×1080 and refreshes at 60 Hz, how many individual frames does it display per second?","answer":"60","explanation":"The refresh rate directly tells you frames per second. 60 Hz = 60 frames drawn per second. Each frame contains 1920×1080 = 2,073,600 pixels that must be rendered every 1/60th of a second."},

    {"type":"mcq","q":"What visual artifact occurs when a display's refresh rate is not synchronized with the GPU's frame output rate?","options":["Color banding","Screen tearing","Moire patterns","Pixelation"],"answer":"Screen tearing","explanation":"Screen tearing happens when the GPU pushes a new frame while the monitor is mid-draw, creating a visible horizontal split where the top shows one frame and the bottom shows another. V-Sync and adaptive sync technologies fix this."},
  ],
  tca: [
    {"type":"fillInTheBlank","q":"Given the string ABABABAB, show the dictionary updates during LZW compression, step by step, and produce the final output code sequence.","answer":"65,66,256,258,66","explanation":"Calculated by walking through LZW algorithm step by step. Output sequence: 65 (A), 66 (B), 256 (AB), 258 (ABA), 66 (B)."},
    {"type":"mcq","q":"Why does an LCD display use an RGBG subpixel arrangement instead of standard RGB?","options":["To reduce power consumption","To make colors appear more natural","To improve sharpness and human eye perception of green","To allow for better contrast in grayscale images"],"answer":"To improve sharpness and human eye perception of green","explanation":"The human eye is most sensitive to green, so pentile/RGBG arrangements dedicate more subpixels to green to boost perceived resolution."},
    {"type":"trueFalse","q":"Increasing image contrast always improves image quality without any drawbacks.","answer":"False","explanation":"Too much contrast causes clipping or saturation, destroying highlight and shadow details."},
    {"type":"mcq","q":"LZW compression works best when:","options":["The input is purely random","The input contains no repeated patterns","The input contains frequently repeated sequences","The input is extremely short"],"answer":"The input contains frequently repeated sequences","explanation":"LZW dynamically builds a dictionary of repeating patterns, making it highly effective for repetitive text or data."},
    {"type":"fillInTheBlank","q":"A string of \"advantage\" is encoded using Huffman coding. Assume the total number of bits required after encoding is 24 bits, while the original string was stored using 8-bit ASCII per character. Calculate the compression ratio and express it as a percentage.","answer":"300","explanation":"Original (9 chars * 8) = 72 bits. Compressed = 24 bits. Ratio = 72 / 24 = 3, which is 300%."},
    {"type":"fillInTheBlank","q":"The human eye is more sensitive to the color ____, which is why modern LCD screens use the RGBG subpixel arrangement.","answer":"green","explanation":"The biological peak sensitivity of the human eye falls squarely on green wavelengths."},
    {"type":"matchFollowing","q":"Match the following image processing techniques with their effects:","pairs":[{"left":"Gaussian Blur","right":"Smooths noise by averaging neighboring pixels"},{"left":"Edge Detection (Canny)","right":"Highlights significant intensity changes"},{"left":"Histogram Equalization","right":"Redistributes brightness levels for uniform contrast"},{"left":"Convolution Filtering","right":"Uses a kernel matrix to apply spatial effects"}],"explanation":"Each filter alters pixel configurations differently using mathematical operations."},
    {"type":"trueFalse","q":"An image file of 200 KB is compressed to 50 KB using a lossless method. The compression ratio is 4:1.","answer":"True","explanation":"200 KB / 50 KB = 4. The ratio is exactly 4:1."},
    {"type":"mcq","q":"What is the primary reason for analyzing an image histogram?","options":["To enhance the color intensity of an image","To measure an image’s brightness distribution","To determine the exact pixel size of an image","To count the number of objects in an image"],"answer":"To measure an image’s brightness distribution","explanation":"A histogram graphically charts pixel brightness values, showing exposure levels."},
    {"type":"mcq","q":"In image sharpening using the Laplacian operator, the final enhanced image is obtained by:","options":["Adding the Laplacian filtered image to the original image","Subtracting the Laplacian filtered image from the original image","Dividing the original image by the Laplacian result","Multiplying the Laplacian by a Gaussian kernel"],"answer":"Subtracting the Laplacian filtered image from the original image","explanation":"Subtracting the negative Laplacian isolates and amplifies the edges relative to the original."},
    {"type":"trueFalse","q":"Edge detection is an example of a spatial filtering technique used in image processing.","answer":"True","explanation":"Edge detection kernels operate on spatial pixel neighborhoods directly."},
    {"type":"mcq","q":"What change in an image histogram suggests a loss of information?","options":["Histogram becomes smoother","Histogram has missing bars or gaps","Histogram shifts entirely to the right","Histogram remains unchanged"],"answer":"Histogram has missing bars or gaps","explanation":"Missing bars point to quantization limits, clipping, or missing tonal shifts due to harsh mathematical enhancements."},
    {"type":"fillInTheBlank","q":"If a Huffman code uses 3 bits on average per symbol for a dataset of 2000 symbols, what is the total compressed size in bits?","answer":"6000","explanation":"2000 symbols * 3 bits = 6000 total bits."},
    {"type":"mcq","q":"In Huffman coding, what determines the length of a character’s binary code?","options":["The total number of unique characters","The ASCII value of the character","The frequency of occurrence in the text","The position of the character in the input string"],"answer":"The frequency of occurrence in the text","explanation":"The most frequent characters get the shortest codes, ensuring maximum compression."},
    {"type":"fillInTheBlank","q":"John applies the given 3x3 filter to the grayscale image. Calculate the new value for the central pixel after convolution. (Hint: Multiply each pixel value by the corresponding filter weight and sum the results.)<br><pre class='matrix-box'>\nImage Pixels:     Filter Weights:\n[ 1,  2,  1 ]     [ 0,  1,  0 ]\n[ 2,  0,  2 ]  x  [ 1,  1,  1 ]\n[ 1,  2,  1 ]     [ 0,  1,  0 ]\n</pre>","answer":"8","explanation":"Central convolution sums the weighted multiplications. (1*0) + (2*1) + (1*0) + (2*1) + (0*1) + (2*1) + (1*0) + (2*1) + (1*0) = 8."},
    {"type":"trueFalse","q":"In an RGB subpixel arrangement, each pixel is made up of equally sized red, green, and blue subpixels.","answer":"True","explanation":"A traditional standard RGB stripe perfectly splits the 3 colors evenly."},
    {"type":"mcq","q":"What happens when an image is over-processed during enhancement?","options":["Irreversible distortion occurs due to lost details","Image gains more colors than it originally had","Image details improve significantly","Histogram becomes more uniform"],"answer":"Irreversible distortion occurs due to lost details","explanation":"Extreme enhancements heavily clip data, turning subtle textures into solid blocks."},
    {"type":"mcq","q":"Which of the following statements best describes Laplacian image enhancement?","options":["It sharpens an image by emphasizing edges and fine details","It performs histogram equalization to enhance contrast","It blurs high-frequency components of an image","It reduces noise through Gaussian smoothing"],"answer":"It sharpens an image by emphasizing edges and fine details","explanation":"The Laplacian operator calculates 2nd-order derivatives, highly targeting rapid pixel shifts."},
    {"type":"fillInTheBlank","q":"To ___ an RGB color, we increase the difference between the most and least intense color channels while keeping the brightness unchanged.","answer":"saturate","explanation":"Extending the relative range makes the primary color pop, raising purity (saturation)."},
    {"type":"fillInTheBlank","q":"John applies a 3x3 averaging filter to the given grayscale image. Calculate the new intensity value of the central pixel.<br><pre class='matrix-box'>\nImage Pixels:\n[ 3,  4,  3 ]\n[ 4,  8,  4 ]\n[ 3,  4,  3 ]\n</pre>","answer":"4","explanation":"An averaging filter inherently uses universal 1/9 weights. The sum of the neighbors is (3+4+3+4+8+4+3+4+3) = 36. Averaged (divided by 9) equals 4."},
    {"type":"mcq","q":"What is the first step in the Huffman encoding process?","options":["Assigning random binary codes","Assigning fixed-length codes to characters","Splitting characters into equal parts","Sorting characters by frequency"],"answer":"Sorting characters by frequency","explanation":"You must build a probability table exactly sorting characters from most string appearances to least."},
    {"type":"mcq","q":"What is the main advantage of Huffman coding?","options":["It is only used for image compression","It ensures a fixed-length encoding","It always produces a 1:1 character-to-binary conversion","It assigns shorter codes to more frequent characters"],"answer":"It assigns shorter codes to more frequent characters","explanation":"This variable-rate layout is the core definition of Huffman's success over fixed-ASCII."},
    {"type":"trueFalse","q":"Convolution-based spatial filtering always reduces image noise.","answer":"False","explanation":"Sharpening filters massively amplify noisy pixels."},
    {"type":"fillInTheBlank","q":"Using the LZW method, the word \"advantage\" is encoded, and the resulting compressed bit size is 32 bits. The original ASCII storage required 64 bits. Calculate the compression ratio.","answer":"2","explanation":"64 divided by 32 literally equals a ratio of 2:1."},
    {"type":"mcq","q":"What is the primary reason LZW compression is used?","options":["It requires prior knowledge of character frequencies","It always provides better compression than Huffman coding","It builds a dictionary dynamically for repeated patterns","It replaces characters with fixed-length codes"],"answer":"It builds a dictionary dynamically for repeated patterns","explanation":"This allows it to achieve extreme compression on highly repetitive data strings without an upfront map."},
    {"type":"mcq","q":"What transformations are applied in the given homogeneous transformation matrix?<br><pre class='matrix-box'>\n[ Sx*cos(θ), -Sy*sin(θ), Tx ]\n[ Sx*sin(θ),  Sy*cos(θ), Ty ]\n[         0,          0,  1 ]\n</pre>","options":["Rotation, Scaling, and Translation","Rotation, Translation, and Shearing","Scaling, Rotation, and Reflection","Translation, Rotation, and Scaling"],"answer":"Rotation, Scaling, and Translation","explanation":"Sx/Sy dictate Scaling, sin/cos dictate Rotation, and Tx/Ty dictate Translation offsets."},
    {"type":"mcq","q":"What type of image processing technique is best suited for detecting cracks in eggs using back-light images?","options":["Histogram equalization","Color thresholding","Fourier Transform","Edge detection (Sobel or Canny)"],"answer":"Edge detection (Sobel or Canny)","explanation":"Cracks manifest as distinct, sharp rapid shifts in pixel intensity which edge detectors instantly mathematically trap."},
    {"type":"trueFalse","q":"In homogeneous transformation, applying translation before rotation results in a different final position than applying rotation before translation.","answer":"True","explanation":"Matrix multiplication is strictly Non-Commutative."},
    {"type":"mcq","q":"What is the purpose of spatial filtering in image processing?","options":["To detect and enhance features like edges or smooth images","To change the image resolution","To modify pixel intensities independently","To convert an image into a binary format"],"answer":"To detect and enhance features like edges or smooth images","explanation":"Spatial filters operate via convolution directly onto raw pixel clusters mapping local trends."},
    {"type":"matchFollowing","q":"Match the following terms with their correct descriptions:","pairs":[{"left":"Huffman Coding","right":"Uses variable-length binary codes based on character frequency"},{"left":"LZW Compression","right":"Creates a dictionary of repeating sequences dynamically"},{"left":"Lossless Encoding","right":"Ensures that no data is lost during compression"},{"left":"ASCII Encoding","right":"Uses fixed-length 8-bit binary representation for characters"}],"explanation":"Memorizing algorithmic characteristics."},
    {"type":"matchFollowing","q":"Match the following image processing techniques with their effects:","pairs":[{"left":"Contrast Enhancement","right":"Expands brightness range, making details clearer"},{"left":"Histogram Equalization","right":"Redistributes brightness levels for uniform contrast"},{"left":"Clipping","right":"Cuts off pixel values at extremes, causing detail loss"},{"left":"Saturation Adjustment","right":"Alters color intensity without changing brightness"}],"explanation":"Understanding exactly how mathematical bounds apply visually to the display channel."},
    {"type":"trueFalse","q":"Fully saturating an RGB color increases its brightness.","answer":"False","explanation":"Saturation only controls the purity (vividness vs gray tone). Luminance controls the brightness independant of purity."},
  ]
};
